/*
** This file is part of eOn.
**
** SPDX-License-Identifier: BSD-3-Clause
**
** Copyright (c) 2010--present, eOn Development Team
** All rights reserved.
**
** Repo:
** https://github.com/TheochemUI/eOn
*/
#include "ConFileIO.h"
#include "EonLogger.h"
#include "HelperFunctions.h"
#include "Matter.h"
#include "SafeMath.h"

#include <cmath>
#include <cstring>
#include <filesystem>
#include <format>
#include <fstream>
#include <iostream>
#include <string>

namespace {

namespace fs = std::filesystem;

std::string strip_nl(const std::string &s) {
  std::string str(s);
  while (!str.empty() && (str.back() == '\n' || str.back() == '\r'))
    str.pop_back();
  return str;
}

std::string canonical_generator_header(const std::string &header) {
  auto stripped = strip_nl(header);
  if (!stripped.empty()) {
    return stripped;
  }
  return "Generated by eOn";
}

std::string ensure_extension(std::string filename, std::string_view ext) {
  fs::path path(filename);
  // Keep compound suffixes like .con.gz / .con.zst for readcon compression.
  const auto name = path.filename().string();
  const bool has_compound =
      name.size() > ext.size() && (name.ends_with(std::string(ext) + ".gz") ||
                                   name.ends_with(std::string(ext) + ".zst"));
  if (!has_compound && path.extension() != ext) {
    path += ext;
  }
  return path.string();
}

std::string symbol_for_z(long atomic_nr) {
  return readcon::z_to_symbol(static_cast<uint64_t>(atomic_nr));
}

void apply_frame_metadata(readcon::ConFrameBuilder &builder,
                          const eonc::io::ConFrameMetadata *metadata) {
  if (metadata == nullptr) {
    return;
  }
  if (metadata->raw_json && !metadata->raw_json->empty()) {
    builder.set_metadata_json(*metadata->raw_json);
  }
  if (metadata->energy) {
    builder.set_energy(*metadata->energy);
  }
  if (metadata->frame_index) {
    builder.set_frame_index(*metadata->frame_index);
  }
  if (metadata->time) {
    builder.set_time(*metadata->time);
  }
  if (metadata->timestep) {
    builder.set_timestep(*metadata->timestep);
  }
  if (metadata->neb_bead) {
    builder.set_neb_bead(*metadata->neb_bead);
  }
  if (metadata->neb_band) {
    builder.set_neb_band(*metadata->neb_band);
  }
  if (metadata->potential_type && !metadata->potential_type->empty()) {
    builder.set_string_metadata("potential_type", *metadata->potential_type);
  }
  for (const auto &[key, value] : metadata->scalars) {
    builder.set_scalar_metadata(key, value);
  }
  for (const auto &[key, value] : metadata->strings) {
    builder.set_string_metadata(key, value);
  }
}

bool write_frames(const fs::path &path, std::vector<readcon::ConFrame> frames,
                  uint8_t precision) {
  try {
    // readcon-core >=0.13: route .con.gz / .con.zst via compression codec.
    const auto compression =
        readcon::ConFrameWriter::compression_from_extension(path);
    readcon::ConFrameWriter writer(path, compression, precision);
    writer.extend(frames);
    return true;
  } catch (const std::exception &e) {
    EONC_LOG_ERROR("Failed to write {}: {}", path.string(), e.what());
    return false;
  }
}

} // namespace

namespace eonc::io {

ConFrameMetadata metadata_from_frame(const readcon::ConFrame &frame) {
  ConFrameMetadata meta;
  meta.energy = frame.energy_opt();
  meta.frame_index = frame.frame_index_opt();
  meta.time = frame.time_opt();
  meta.timestep = frame.timestep_opt();
  meta.neb_bead = frame.neb_bead_opt();
  meta.neb_band = frame.neb_band_opt();
  meta.potential_type = frame.potential_type();
  const auto json = frame.metadata_json();
  if (!json.empty() && json != "{}") {
    meta.raw_json = json;
  }
  return meta;
}

std::pair<std::array<double, 3>, std::array<double, 3>>
cell_to_lengths_angles(const Matter &m) {
  // Friend of Matter: may read private cell matrix.
  std::array<double, 3> lengths;
  lengths[0] = m.cell.row(0).norm();
  lengths[1] = m.cell.row(1).norm();
  lengths[2] = m.cell.row(2).norm();
  std::array<double, 3> angles;
  angles[0] = eonc::safemath::safe_acos(eonc::safemath::safe_div(
                  m.cell.row(0).dot(m.cell.row(1)), lengths[0] * lengths[1])) *
              180.0 / eonc::helpers::pi;
  angles[1] = eonc::safemath::safe_acos(eonc::safemath::safe_div(
                  m.cell.row(0).dot(m.cell.row(2)), lengths[0] * lengths[2])) *
              180.0 / eonc::helpers::pi;
  angles[2] = eonc::safemath::safe_acos(eonc::safemath::safe_div(
                  m.cell.row(1).dot(m.cell.row(2)), lengths[1] * lengths[2])) *
              180.0 / eonc::helpers::pi;
  return {lengths, angles};
}

bool matter2con(Matter &m, std::string filename, bool append,
                const ConFrameMetadata *metadata) {
  filename = ensure_extension(std::move(filename), ".con");

  if (m.usePeriodicBoundaries) {
    m.applyPeriodicBoundary();
  }

  auto [lengths, angles_deg] = cell_to_lengths_angles(m);

  readcon::ConFrameBuilder builder(
      {lengths[0], lengths[1], lengths[2]},
      {angles_deg[0], angles_deg[1], angles_deg[2]},
      {canonical_generator_header(m.headerCon[0]), strip_nl(m.headerCon[1])},
      {strip_nl(m.headerCon[3]), strip_nl(m.headerCon[4])});

  // Auto-attach total energy when the potential cache is current and the
  // caller did not already supply energy metadata.
  ConFrameMetadata auto_meta;
  const ConFrameMetadata *meta_ptr = metadata;
  if (!m.needsForceUpdate()) {
    if (metadata == nullptr) {
      auto_meta.energy = m.getPotentialEnergy();
      meta_ptr = &auto_meta;
    } else if (!metadata->energy) {
      auto_meta = *metadata;
      auto_meta.energy = m.getPotentialEnergy();
      meta_ptr = &auto_meta;
    }
  }
  apply_frame_metadata(builder, meta_ptr);

  // Forces section when the cache is valid (movies/checkpoints carry forces).
  const bool write_forces = !m.needsForceUpdate();
  const AtomMatrix *forces_ptr = write_forces ? &m.getForcesRaw() : nullptr;

  const long n = m.numberOfAtoms();
  for (long i = 0; i < n; i++) {
    const bool fixed = m.getFixed(i) != 0;
    const std::array<bool, 3> fixed_axes{fixed, fixed, fixed};
    std::optional<std::array<double, 3>> force;
    if (forces_ptr != nullptr) {
      force = std::array<double, 3>{(*forces_ptr)(i, 0), (*forces_ptr)(i, 1),
                                    (*forces_ptr)(i, 2)};
    }
    builder.add_atom(symbol_for_z(m.getAtomicNr(i)), m.getPosition(i, 0),
                     m.getPosition(i, 1), m.getPosition(i, 2), fixed_axes,
                     static_cast<uint64_t>(m.atomIndex(i)), m.getMass(i),
                     /*velocity=*/std::nullopt, force);
  }

  auto frame = builder.build();
  std::vector<readcon::ConFrame> frames;
  if (append) {
    if (fs::exists(filename)) {
      try {
        frames = readcon::read_all_frames(filename);
      } catch (const std::exception &e) {
        EONC_LOG_ERROR("Failed to append to {}: {}", filename, e.what());
        return false;
      }
    }
  }
  frames.push_back(std::move(frame));
  return write_frames(filename, std::move(frames), 17);
}

bool con2matter(Matter &m, std::string filename) {
  filename = ensure_extension(std::move(filename), ".con");
  try {
    auto frame = readcon::read_first_frame(filename);
    return con2matter(m, frame, nullptr);
  } catch (const std::exception &e) {
    EONC_LOG_ERROR("Failed to read {}: {}", filename, e.what());
    return false;
  }
}

bool con2matter(Matter &m, const readcon::ConFrame &frame,
                ConFrameMetadata *out_metadata) {
  const auto &atoms = frame.atoms();
  const auto &lengths = frame.cell();
  const auto &angles_deg = frame.angles();
  const auto &prebox = frame.prebox_header();
  const auto &postbox = frame.postbox_header();

  m.headerCon[0] = prebox[0] + "\n";
  m.headerCon[1] = prebox[1] + "\n";
  m.headerCon[3] = postbox[0] + "\n";
  m.headerCon[4] = postbox[1] + "\n";

  double angles[3] = {angles_deg[0], angles_deg[1], angles_deg[2]};
  if (angles[0] == 90.0 && angles[1] == 90.0 && angles[2] == 90.0) {
    m.cell.setZero();
    m.cell(0, 0) = lengths[0];
    m.cell(1, 1) = lengths[1];
    m.cell(2, 2) = lengths[2];
  } else {
    angles[0] *= eonc::helpers::pi / 180.0;
    angles[1] *= eonc::helpers::pi / 180.0;
    angles[2] *= eonc::helpers::pi / 180.0;

    m.cell(0, 0) = 1.0;
    m.cell(1, 0) = cos(angles[0]);
    m.cell(1, 1) = sin(angles[0]);
    m.cell(2, 0) = cos(angles[1]);
    m.cell(2, 1) =
        (cos(angles[2]) - m.cell(1, 0) * m.cell(2, 0)) / m.cell(1, 1);
    m.cell(2, 2) = eonc::safemath::safe_sqrt(1.0 - pow(m.cell(2, 0), 2) -
                                             pow(m.cell(2, 1), 2));

    m.cell(0, 0) *= lengths[0];
    m.cell(1, 0) *= lengths[1];
    m.cell(1, 1) *= lengths[1];
    m.cell(2, 0) *= lengths[2];
    m.cell(2, 1) *= lengths[2];
    m.cell(2, 2) *= lengths[2];
  }
  m.cellInverse = m.cell.inverse();
  m.headerCon[2] =
      std::format("{} {} {}\n", angles_deg[0], angles_deg[1], angles_deg[2]);

  m.resize(static_cast<long>(atoms.size()));
  AtomMatrix forces =
      AtomMatrix::Zero(static_cast<Eigen::Index>(atoms.size()), 3);
  AtomMatrix velocities =
      AtomMatrix::Zero(static_cast<Eigen::Index>(atoms.size()), 3);
  bool any_force = false;
  bool any_velocity = false;

  for (size_t i = 0; i < atoms.size(); ++i) {
    const auto &atom = atoms[i];
    m.positions(i, 0) = atom.x;
    m.positions(i, 1) = atom.y;
    m.positions(i, 2) = atom.z;
    m.setMass(i, atom.mass);
    m.setAtomicNr(i, static_cast<int>(atom.atomic_number));
    const auto fixed = atom.fixed_mask();
    const bool is_fixed = fixed[0] || fixed[1] || fixed[2];
    m.setFixed(i, is_fixed ? 1 : 0);
    m.atomIndex(i) = static_cast<int>(atom.atom_id);

    if (auto vel = atom.velocity()) {
      any_velocity = true;
      velocities(static_cast<Eigen::Index>(i), 0) = (*vel)[0];
      velocities(static_cast<Eigen::Index>(i), 1) = (*vel)[1];
      velocities(static_cast<Eigen::Index>(i), 2) = (*vel)[2];
    }
    if (auto force = atom.force()) {
      any_force = true;
      forces(static_cast<Eigen::Index>(i), 0) = (*force)[0];
      forces(static_cast<Eigen::Index>(i), 1) = (*force)[1];
      forces(static_cast<Eigen::Index>(i), 2) = (*force)[2];
    }
  }

  if (any_velocity || frame.has_velocities()) {
    m.setVelocities(velocities);
  }

  const auto meta = metadata_from_frame(frame);
  if (out_metadata != nullptr) {
    *out_metadata = meta;
  }
  // Trust dumped energy; setComputedPotential may adjust net force, so restore
  // file forces afterwards for exact force round-trips.
  if (meta.energy) {
    m.setComputedPotential(*meta.energy, 0.0);
  } else {
    m.recomputePotential = true;
  }
  if (any_force || frame.has_forces()) {
    m.setForces(forces);
    if (meta.energy) {
      m.recomputePotential = false;
      m.recomputeMaskedForces = true;
    }
  }

  if (m.usePeriodicBoundaries) {
    m.applyPeriodicBoundary();
  }
  return true;
}

bool matter2convel(Matter &m, std::string filename) {
  filename = ensure_extension(std::move(filename), ".convel");

  if (m.usePeriodicBoundaries) {
    m.applyPeriodicBoundary();
  }

  auto [lengths, angles_deg] = cell_to_lengths_angles(m);

  readcon::ConFrameBuilder builder(
      {lengths[0], lengths[1], lengths[2]},
      {angles_deg[0], angles_deg[1], angles_deg[2]},
      {canonical_generator_header(m.headerCon[0]), strip_nl(m.headerCon[1])},
      {strip_nl(m.headerCon[3]), strip_nl(m.headerCon[4])});

  if (!m.needsForceUpdate()) {
    builder.set_energy(m.getPotentialEnergy());
  }

  const bool write_forces = !m.needsForceUpdate();
  const AtomMatrix *forces_ptr = write_forces ? &m.getForcesRaw() : nullptr;
  const AtomMatrix velocities = m.getVelocities();

  const long n = m.numberOfAtoms();
  for (long i = 0; i < n; i++) {
    const bool fixed = m.getFixed(i) != 0;
    const std::array<bool, 3> fixed_axes{fixed, fixed, fixed};
    std::optional<std::array<double, 3>> vel{
        {velocities(i, 0), velocities(i, 1), velocities(i, 2)}};
    std::optional<std::array<double, 3>> force;
    if (forces_ptr != nullptr) {
      force = std::array<double, 3>{(*forces_ptr)(i, 0), (*forces_ptr)(i, 1),
                                    (*forces_ptr)(i, 2)};
    }
    builder.add_atom(symbol_for_z(m.getAtomicNr(i)), m.getPosition(i, 0),
                     m.getPosition(i, 1), m.getPosition(i, 2), fixed_axes,
                     static_cast<uint64_t>(m.atomIndex(i)), m.getMass(i), vel,
                     force);
  }

  auto frame = builder.build();
  std::vector<readcon::ConFrame> frames;
  frames.push_back(std::move(frame));
  return write_frames(filename, std::move(frames), 6);
}

bool convel2matter(Matter &m, std::string filename) {
  filename = ensure_extension(std::move(filename), ".convel");
  try {
    auto frame = readcon::read_first_frame(filename);
    return con2matter(m, frame, nullptr);
  } catch (const std::exception &e) {
    EONC_LOG_ERROR("Failed to read convel {}: {}", filename, e.what());
    return false;
  }
}

void matter2xyz(Matter &m, std::string filename, bool append) {
  FILE *file;
  long int i;
  filename += ".xyz";
  if (append) {
    file = fopen(filename.c_str(), "ab");
  } else {
    file = fopen(filename.c_str(), "wb");
  }
  if (file == 0) {
    std::cerr << "Can't create file " << filename << std::endl;
    exit(1);
  }
  fprintf(file, "%ld\nGenerated by eOn\n", m.numberOfAtoms());

  if (m.usePeriodicBoundaries) {
    m.applyPeriodicBoundary();
  }

  for (i = 0; i < m.numberOfAtoms(); i++) {
    const auto sym = symbol_for_z(m.getAtomicNr(i));
    fprintf(file, "%s\t%11.6f\t%11.6f\t%11.6f\n", sym.c_str(),
            m.getPosition(i, 0), m.getPosition(i, 1), m.getPosition(i, 2));
  }
  fclose(file);
}

void writeTibble(Matter &m, std::string fname) {
  AtomMatrix fSys = m.getForces();
  std::ofstream out(fname);
  double eSys = m.getPotentialEnergy();
  AtomMatrix pos = m.getPositions();
  out << "x y z fx fy fz energy mass symbol atmID fixed\n";
  for (auto idx{0}; idx < m.numberOfAtoms(); idx++) {
    out << std::format("{} {} {} {} {} {} {} {} {} {} {}\n", pos.row(idx)[0],
                       pos.row(idx)[1], pos.row(idx)[2], fSys.row(idx)[0],
                       fSys.row(idx)[1], fSys.row(idx)[2], eSys, m.getMass(idx),
                       symbol_for_z(m.getAtomicNr(idx)), (idx + 1),
                       m.getFixed(idx));
  }
}

} // namespace eonc::io
