/*
** This file is part of eOn.
**
** SPDX-License-Identifier: BSD-3-Clause
**
** Copyright (c) 2010--present, eOn Development Team
** All rights reserved.
**
** Repo:
** https://github.com/TheochemUI/eOn
*/
#include "ConFileIO.h"
#include "Eigen.h"
#include "EonLogger.h"
#include "HelperFunctions.h"
#include "Matter.h"
#include "SafeMath.h"

#include <cmath>
#include <cstring>
#include <filesystem>
#include <format>
#include <fstream>
#include <iostream>
#include <string>
#include <vector>

namespace {

namespace fs = std::filesystem;

std::string strip_nl(const std::string &s) {
  std::string str(s);
  while (!str.empty() && (str.back() == '\n' || str.back() == '\r'))
    str.pop_back();
  return str;
}

std::string canonical_generator_header(const std::string &header) {
  auto stripped = strip_nl(header);
  if (!stripped.empty()) {
    return stripped;
  }
  return "Generated by eOn";
}

std::string ensure_extension(std::string filename, std::string_view ext) {
  fs::path path(filename);
  // Keep compound suffixes like .con.gz / .con.zst for readcon compression.
  const auto name = path.filename().string();
  const bool has_compound =
      name.size() > ext.size() && (name.ends_with(std::string(ext) + ".gz") ||
                                   name.ends_with(std::string(ext) + ".zst"));
  if (!has_compound && path.extension() != ext) {
    path += ext;
  }
  return path.string();
}

std::string symbol_for_z(long atomic_nr) {
  return readcon::z_to_symbol(static_cast<uint64_t>(atomic_nr));
}

/// Copy an Nx3 RowMajor AtomMatrix into a flat [x0,y0,z0,...] buffer for
/// readcon bulk setters (set_*_from_flat).
std::vector<double> flat_row_major(const AtomMatrix &m) {
  const auto n = static_cast<size_t>(m.rows());
  std::vector<double> flat(n * 3);
  // AtomMatrix is already RowMajor Nx3 — one contiguous memcpy.
  std::memcpy(flat.data(), m.data(), flat.size() * sizeof(double));
  return flat;
}

void apply_frame_metadata(readcon::ConFrameBuilder &builder,
                          const eonc::io::ConFrameMetadata *metadata) {
  if (metadata == nullptr) {
    return;
  }
  if (metadata->raw_json && !metadata->raw_json->empty()) {
    builder.set_metadata_json(*metadata->raw_json);
  }
  if (metadata->energy) {
    builder.set_energy(*metadata->energy);
  }
  if (metadata->frame_index) {
    builder.set_frame_index(*metadata->frame_index);
  }
  if (metadata->time) {
    builder.set_time(*metadata->time);
  }
  if (metadata->timestep) {
    builder.set_timestep(*metadata->timestep);
  }
  if (metadata->neb_bead) {
    builder.set_neb_bead(*metadata->neb_bead);
  }
  if (metadata->neb_band) {
    builder.set_neb_band(*metadata->neb_band);
  }
  if (metadata->potential_type && !metadata->potential_type->empty()) {
    builder.set_string_metadata("potential_type", *metadata->potential_type);
  }
  for (const auto &[key, value] : metadata->scalars) {
    builder.set_scalar_metadata(key, value);
  }
  for (const auto &[key, value] : metadata->strings) {
    builder.set_string_metadata(key, value);
  }
}

bool write_frames(const fs::path &path, std::vector<readcon::ConFrame> frames,
                  uint8_t precision) {
  try {
    const auto compression =
        readcon::ConFrameWriter::compression_from_extension(path);
    readcon::ConFrameWriter writer(path, compression, precision);
    writer.extend(frames);
    return true;
  } catch (const std::exception &e) {
    EONC_LOG_ERROR("Failed to write {}: {}", path.string(), e.what());
    return false;
  }
}

/**
 * Preferred write path for readcon-core >=0.13 mutation API:
 *  1. seed atoms (symbol / fixed mask / id / mass)
 *  2. set_positions_from_flat (bulk)
 *  3. set_forces_from_flat when the pot cache is current
 *  4. set_atom_velocity per atom when requested
 *  5. frame metadata via set_energy / set_*_metadata
 *
 * atom_ids + prebox/postbox are passed in so this helper only needs Matter's
 * public surface (private headerCon / atomIndex stay in the friend callers).
 */
readcon::ConFrame frame_from_matter(Matter &m,
                                    const std::array<std::string, 2> &prebox,
                                    const std::array<std::string, 2> &postbox,
                                    const std::vector<uint64_t> &atom_ids,
                                    const eonc::io::ConFrameMetadata *metadata,
                                    bool with_velocities) {
  auto [lengths, angles_deg] = eonc::io::cell_to_lengths_angles(m);

  readcon::ConFrameBuilder builder(
      {lengths[0], lengths[1], lengths[2]},
      {angles_deg[0], angles_deg[1], angles_deg[2]}, prebox, postbox);

  eonc::io::ConFrameMetadata auto_meta;
  const eonc::io::ConFrameMetadata *meta_ptr = metadata;
  if (!m.needsForceUpdate()) {
    if (metadata == nullptr) {
      auto_meta.energy = m.getPotentialEnergy();
      meta_ptr = &auto_meta;
    } else if (!metadata->energy) {
      auto_meta = *metadata;
      auto_meta.energy = m.getPotentialEnergy();
      meta_ptr = &auto_meta;
    }
  }
  apply_frame_metadata(builder, meta_ptr);

  const long n = m.numberOfAtoms();
  if (atom_ids.size() != static_cast<size_t>(n)) {
    throw std::runtime_error(
        "frame_from_matter: atom_ids size does not match numberOfAtoms");
  }

  // (1) Seed identity fields. Geometry/dynamics via bulk/in-place setters.
  for (long i = 0; i < n; ++i) {
    const bool fixed = m.getFixed(i) != 0;
    builder.add_atom(symbol_for_z(m.getAtomicNr(i)), 0.0, 0.0, 0.0,
                     std::array<bool, 3>{fixed, fixed, fixed},
                     atom_ids[static_cast<size_t>(i)], m.getMass(i));
  }

  // (2) Bulk positions — AtomMatrix is RowMajor Nx3, matching the flat layout.
  builder.set_positions_from_flat(flat_row_major(m.getPositions()));

  // (3) Bulk forces when the force cache is current.
  if (!m.needsForceUpdate()) {
    builder.set_forces_from_flat(flat_row_major(m.getForcesRaw()));
  }

  // (4) Velocities via set_atom_velocity (declares the velocities section).
  if (with_velocities) {
    const AtomMatrix vel = m.getVelocities();
    for (long i = 0; i < n; ++i) {
      builder.set_atom_velocity(static_cast<size_t>(i),
                                {vel(i, 0), vel(i, 1), vel(i, 2)});
    }
  }

  return builder.build();
}

} // namespace

namespace eonc::io {

ConFrameMetadata metadata_from_frame(const readcon::ConFrame &frame) {
  ConFrameMetadata meta;
  meta.energy = frame.energy_opt();
  meta.frame_index = frame.frame_index_opt();
  meta.time = frame.time_opt();
  meta.timestep = frame.timestep_opt();
  meta.neb_bead = frame.neb_bead_opt();
  meta.neb_band = frame.neb_band_opt();
  meta.potential_type = frame.potential_type();
  const auto json = frame.metadata_json();
  if (!json.empty() && json != "{}") {
    meta.raw_json = json;
  }
  return meta;
}

std::pair<std::array<double, 3>, std::array<double, 3>>
cell_to_lengths_angles(const Matter &m) {
  std::array<double, 3> lengths;
  lengths[0] = m.cell.row(0).norm();
  lengths[1] = m.cell.row(1).norm();
  lengths[2] = m.cell.row(2).norm();
  std::array<double, 3> angles;
  angles[0] = eonc::safemath::safe_acos(eonc::safemath::safe_div(
                  m.cell.row(0).dot(m.cell.row(1)), lengths[0] * lengths[1])) *
              180.0 / eonc::helpers::pi;
  angles[1] = eonc::safemath::safe_acos(eonc::safemath::safe_div(
                  m.cell.row(0).dot(m.cell.row(2)), lengths[0] * lengths[2])) *
              180.0 / eonc::helpers::pi;
  angles[2] = eonc::safemath::safe_acos(eonc::safemath::safe_div(
                  m.cell.row(1).dot(m.cell.row(2)), lengths[1] * lengths[2])) *
              180.0 / eonc::helpers::pi;
  return {lengths, angles};
}

bool matter2con(Matter &m, std::string filename, bool append,
                const ConFrameMetadata *metadata) {
  filename = ensure_extension(std::move(filename), ".con");

  if (m.usePeriodicBoundaries) {
    m.applyPeriodicBoundary();
  }

  const long n = m.numberOfAtoms();
  std::vector<uint64_t> atom_ids(static_cast<size_t>(n));
  for (long i = 0; i < n; ++i) {
    atom_ids[static_cast<size_t>(i)] = static_cast<uint64_t>(m.atomIndex(i));
  }
  const std::array<std::string, 2> prebox{
      canonical_generator_header(m.headerCon[0]), strip_nl(m.headerCon[1])};
  const std::array<std::string, 2> postbox{strip_nl(m.headerCon[3]),
                                           strip_nl(m.headerCon[4])};

  auto frame = frame_from_matter(m, prebox, postbox, atom_ids, metadata,
                                 /*with_velocities=*/false);

  std::vector<readcon::ConFrame> frames;
  if (append) {
    if (fs::exists(filename)) {
      try {
        frames = readcon::read_all_frames(filename);
      } catch (const std::exception &e) {
        EONC_LOG_ERROR("Failed to append to {}: {}", filename, e.what());
        return false;
      }
    }
  }
  frames.push_back(std::move(frame));
  return write_frames(filename, std::move(frames), 17);
}

bool con2matter(Matter &m, std::string filename) {
  filename = ensure_extension(std::move(filename), ".con");
  try {
    auto frame = readcon::read_first_frame(filename);
    return con2matter(m, frame, nullptr);
  } catch (const std::exception &e) {
    EONC_LOG_ERROR("Failed to read {}: {}", filename, e.what());
    return false;
  }
}

bool con2matter(Matter &m, const readcon::ConFrame &frame,
                ConFrameMetadata *out_metadata) {
  const auto &atoms = frame.atoms();
  const auto &lengths = frame.cell();
  const auto &angles_deg = frame.angles();
  const auto &prebox = frame.prebox_header();
  const auto &postbox = frame.postbox_header();

  m.headerCon[0] = prebox[0] + "\n";
  m.headerCon[1] = prebox[1] + "\n";
  m.headerCon[3] = postbox[0] + "\n";
  m.headerCon[4] = postbox[1] + "\n";

  double angles[3] = {angles_deg[0], angles_deg[1], angles_deg[2]};
  if (angles[0] == 90.0 && angles[1] == 90.0 && angles[2] == 90.0) {
    Matrix3d cell = Matrix3d::Zero();
    cell(0, 0) = lengths[0];
    cell(1, 1) = lengths[1];
    cell(2, 2) = lengths[2];
    m.setCell(cell);
  } else {
    angles[0] *= eonc::helpers::pi / 180.0;
    angles[1] *= eonc::helpers::pi / 180.0;
    angles[2] *= eonc::helpers::pi / 180.0;

    Matrix3d cell = Matrix3d::Zero();
    cell(0, 0) = 1.0;
    cell(1, 0) = cos(angles[0]);
    cell(1, 1) = sin(angles[0]);
    cell(2, 0) = cos(angles[1]);
    cell(2, 1) = (cos(angles[2]) - cell(1, 0) * cell(2, 0)) / cell(1, 1);
    cell(2, 2) = eonc::safemath::safe_sqrt(1.0 - pow(cell(2, 0), 2) -
                                           pow(cell(2, 1), 2));

    cell(0, 0) *= lengths[0];
    cell(1, 0) *= lengths[1];
    cell(1, 1) *= lengths[1];
    cell(2, 0) *= lengths[2];
    cell(2, 1) *= lengths[2];
    cell(2, 2) *= lengths[2];
    m.setCell(cell);
  }
  m.headerCon[2] =
      std::format("{} {} {}\n", angles_deg[0], angles_deg[1], angles_deg[2]);

  const auto n = static_cast<Eigen::Index>(atoms.size());
  m.resize(static_cast<long>(atoms.size()));

  // Assemble full matrices then use Matter setters instead of poking private
  // storage field-by-field.
  AtomMatrix positions = AtomMatrix::Zero(n, 3);
  AtomMatrix forces = AtomMatrix::Zero(n, 3);
  AtomMatrix velocities = AtomMatrix::Zero(n, 3);
  bool any_force = false;
  bool any_velocity = false;

  for (Eigen::Index i = 0; i < n; ++i) {
    const auto &atom = atoms[static_cast<size_t>(i)];
    positions(i, 0) = atom.x;
    positions(i, 1) = atom.y;
    positions(i, 2) = atom.z;
    m.setMass(static_cast<long>(i), atom.mass);
    m.setAtomicNr(static_cast<long>(i), static_cast<int>(atom.atomic_number));
    // Prefer fixed_mask() over the deprecated is_fixed aggregate.
    const auto fixed = atom.fixed_mask();
    m.setFixed(static_cast<long>(i),
               (fixed[0] || fixed[1] || fixed[2]) ? 1 : 0);
    m.atomIndex(static_cast<long>(i)) = static_cast<int>(atom.atom_id);

    if (auto vel = atom.velocity()) {
      any_velocity = true;
      velocities(i, 0) = (*vel)[0];
      velocities(i, 1) = (*vel)[1];
      velocities(i, 2) = (*vel)[2];
    }
    if (auto force = atom.force()) {
      any_force = true;
      forces(i, 0) = (*force)[0];
      forces(i, 1) = (*force)[1];
      forces(i, 2) = (*force)[2];
    }
  }

  // setPositions applies PBC when enabled and marks the pot dirty; we re-trust
  // file energy/forces below when present.
  m.setPositions(positions);

  if (any_velocity || frame.has_velocities()) {
    m.setVelocities(velocities);
  }

  const auto meta = metadata_from_frame(frame);
  if (out_metadata != nullptr) {
    *out_metadata = meta;
  }
  // Trust dumped energy; setComputedPotential may adjust net force, so restore
  // file forces afterwards for exact force round-trips.
  if (meta.energy) {
    m.setComputedPotential(*meta.energy, 0.0);
  } else {
    m.recomputePotential = true;
  }
  if (any_force || frame.has_forces()) {
    m.setForces(forces);
    if (meta.energy) {
      m.recomputePotential = false;
      m.recomputeMaskedForces = true;
    }
  }

  return true;
}

bool matter2convel(Matter &m, std::string filename) {
  filename = ensure_extension(std::move(filename), ".convel");

  if (m.usePeriodicBoundaries) {
    m.applyPeriodicBoundary();
  }

  const long n = m.numberOfAtoms();
  std::vector<uint64_t> atom_ids(static_cast<size_t>(n));
  for (long i = 0; i < n; ++i) {
    atom_ids[static_cast<size_t>(i)] = static_cast<uint64_t>(m.atomIndex(i));
  }
  const std::array<std::string, 2> prebox{
      canonical_generator_header(m.headerCon[0]), strip_nl(m.headerCon[1])};
  const std::array<std::string, 2> postbox{strip_nl(m.headerCon[3]),
                                           strip_nl(m.headerCon[4])};

  auto frame = frame_from_matter(m, prebox, postbox, atom_ids, nullptr,
                                 /*with_velocities=*/true);
  std::vector<readcon::ConFrame> frames;
  frames.push_back(std::move(frame));
  return write_frames(filename, std::move(frames), 6);
}

bool convel2matter(Matter &m, std::string filename) {
  filename = ensure_extension(std::move(filename), ".convel");
  try {
    auto frame = readcon::read_first_frame(filename);
    return con2matter(m, frame, nullptr);
  } catch (const std::exception &e) {
    EONC_LOG_ERROR("Failed to read convel {}: {}", filename, e.what());
    return false;
  }
}

void matter2xyz(Matter &m, std::string filename, bool append) {
  FILE *file;
  long int i;
  filename += ".xyz";
  if (append) {
    file = fopen(filename.c_str(), "ab");
  } else {
    file = fopen(filename.c_str(), "wb");
  }
  if (file == 0) {
    std::cerr << "Can't create file " << filename << std::endl;
    exit(1);
  }
  fprintf(file, "%ld\nGenerated by eOn\n", m.numberOfAtoms());

  if (m.usePeriodicBoundaries) {
    m.applyPeriodicBoundary();
  }

  for (i = 0; i < m.numberOfAtoms(); i++) {
    const auto sym = symbol_for_z(m.getAtomicNr(i));
    fprintf(file, "%s\t%11.6f\t%11.6f\t%11.6f\n", sym.c_str(),
            m.getPosition(i, 0), m.getPosition(i, 1), m.getPosition(i, 2));
  }
  fclose(file);
}

void writeTibble(Matter &m, std::string fname) {
  AtomMatrix fSys = m.getForces();
  std::ofstream out(fname);
  double eSys = m.getPotentialEnergy();
  AtomMatrix pos = m.getPositions();
  out << "x y z fx fy fz energy mass symbol atmID fixed\n";
  for (auto idx{0}; idx < m.numberOfAtoms(); idx++) {
    out << std::format("{} {} {} {} {} {} {} {} {} {} {}\n", pos.row(idx)[0],
                       pos.row(idx)[1], pos.row(idx)[2], fSys.row(idx)[0],
                       fSys.row(idx)[1], fSys.row(idx)[2], eSys, m.getMass(idx),
                       symbol_for_z(m.getAtomicNr(idx)), (idx + 1),
                       m.getFixed(idx));
  }
}

} // namespace eonc::io
