[Main]
job = saddle_search
temperature = 300
random_seed = 706253457

# [Potential]
# potential = metatomic
# [Metatomic]
# model_path = pet-mad-v1.1.0.pt

[Potential]
potential = xtb
[XTBPot]
paramset = GFN2xTB

[Optimizer]
opt_method = lbfgs
converged_force = 0.01
max_iterations = 1000
max_move = 0.05
convergence_metric = norm

[LBFGS]
lbfgs_memory = 25
lbfgs_inverse_curvature = 0.01
lbfgs_auto_scale = true

[Saddle Search]
displace_least_coordinated_weight = 1.0
displace_radius = 3.3
displace_magnitude = 0.01
min_mode_method = dimer
max_energy = 10.0

[Debug]
write_movies = True

[Dimer]
improved = true
opt_method = cg
remove_rotation = False
converged_angle = 0.5
