* About

#+begin_export markdown
[![Build](https://github.com/TheochemUI/eOn/actions/workflows/ci_build_akmc.yml/badge.svg)](https://github.com/TheochemUI/eOn/actions/workflows/ci_build_akmc.yml)
[![codecov](https://codecov.io/gh/TheochemUI/eOn/graph/badge.svg)](https://app.codecov.io/gh/TheochemUI/eOn)
[![Benchmarks](https://img.shields.io/badge/benchmarks-asv--perch-orange)](https://github.com/HaoZeke/asv-perch)
[![License: BSD-3](https://img.shields.io/badge/License-BSD--3-blue.svg)](https://opensource.org/licenses/BSD-3-Clause)
#+end_export

A modern, elegant approach to working with [[https://eondocs.org][eOn]].

** Build
*** Pixi

We provide a [[https://prefix.dev][pixi]] environment for reproducible builds:

#+begin_src bash
pixi install
#+end_src

Then build and install:

#+begin_src bash
pixi run bash -c "meson setup bbdir \
  --prefix=$CONDA_PREFIX --libdir=lib \
  --buildtype release --wipe 2>/dev/null \
  || meson setup bbdir --prefix=$CONDA_PREFIX \
  --libdir=lib --buildtype release"
pixi run meson install -C bbdir
#+end_src

The server is accessed through ~python -m eon.server~. The ~eonclient~ binary
is automatically made available in the activated environment.

** Running Tests
*** Meson

This is the preferred method.

#+begin_src bash
cd client
# in pixi, add --prefix=$CONDA_PREFIX --libdir=lib
meson setup bbdir --buildtype=debug -Dbuild_tests=true
meson test -C bbdir
#+end_src

*** Python (ASV Benchmarks)

Performance benchmarks use [[https://asv.readthedocs.io][ASV]] with results
posted on PRs via [[https://github.com/HaoZeke/asv-perch][asv-perch]]:

#+begin_src bash
# Validate benchmarks
pixi run bash -c "pip install asv && asv check"

# Quick local run
pixi run bash -c "asv machine --yes && \
  asv run -E 'existing:$(which python)' --quick"
#+end_src

* Documentation

The published site is MyST markdown under ~docs/source~, built with Sphinx
([[https://eondocs.org][eondocs.org]]).

To schedule ~eonclient~ through AiiDA, install ~aiida-eon~ and see
~docs/source/user_guide/aiida.md~. That page is the plugin landing in
this tree. In-process Matter work is pyeonclient, not AiiDA.

* Contributing

Run ~pre-commit~ before submitting pull requests:

#+begin_src bash
uvx prek run --all-files
#+end_src

For best results, install the git hook:

#+begin_src bash
uvx prek install
#+end_src

* Testing

We have both ~Catch2~ unit tests, and also ~ApprovalTests~. For adding new
approval tests, first build them with ~meson compile~, run them to approve, and
then re-run to make sure things pass with ~meson test~.

* Citing eOn

If eOn helps your work, please cite:

#+begin_quote
S. T. Chill, M. Welborn, R. Terrell, L. Zhang, J.-C. Berthet, A. Pedersen,
H. Jónsson and G. Henkelman, "EON: software for long time simulations of
atomic scale systems", /Modelling Simul. Mater. Sci. Eng./ *22*, 055002
(2014). [[https://doi.org/10.1088/0965-0393/22/5/055002][doi:10.1088/0965-0393/22/5/055002]]
#+end_quote

#+begin_src bibtex
@article{chillEONSoftwareLong2014,
  title = {{EON}: Software for Long Time Simulations of Atomic Scale Systems},
  author = {Chill, Samuel T and Welborn, Matthew and Terrell, Rye and Zhang, Liang and Berthet, Jean-Claude and Pedersen, Andreas and J{\'o}nsson, Hannes and Henkelman, Graeme},
  year = {2014},
  journal = {Modelling and Simulation in Materials Science and Engineering},
  volume = {22},
  number = {5},
  pages = {055002},
  doi = {10.1088/0965-0393/22/5/055002}
}
#+end_src

GitHub reads the same reference from ~CITATION.cff~.

* License

[[https://opensource.org/licenses/BSD-3-Clause][BSD-3 clause]].
