rgpot_pot = library(
    'rgpot_pot',
    sources: [
        'RgpotPot.cpp',
        'RGPotEngine.cpp',
        'MetatomicEngineLoader.cpp',
        'XTBEngineLoader.cpp',
    ],
    include_directories: _incdirs,
    dependencies: _deps,
    cpp_args: _args,
    link_with: _linkto,
    install: true,
)
