#!/bin/sh
if [ -e config.ini ] 
then
   echo "All input files are ready, start to run this sample job "
else
   echo "Input files are not ready, please run ./init before ./run "
   exit 1
fi
nrun=1
for (( i=1; i<=$nrun; i++ ))
do
./init
../../eon
done
../../eon -n
