/*
** This file is part of eOn.
**
** SPDX-License-Identifier: BSD-3-Clause
**
** Copyright (c) 2010--present, eOn Development Team
** All rights reserved.
**
** Repo:
** https://github.com/TheochemUI/eOn
*/

#include "ConFileIO.h"
#include "Matter.h"
#include "NEBSplineExtrema.h"
#include "Parameters.h"
#include "TestUtils.hpp"
#include "catch2/catch_amalgamated.hpp"
#include <cstdio>
#include <filesystem>
#include <fstream>

namespace tests {

static eonc::helpers::test::QuillTestLogger _quill_setup;

class ConFileIOFixture {
protected:
  Parameters params;
  std::shared_ptr<Potential> pot;
  std::shared_ptr<Matter> original;

  ConFileIOFixture()
      : params{},
        pot{nullptr},
        original{nullptr} {
    params.potential_options.potential = PotType::LJ;
    pot = eonc::helpers::makePotential(PotType::LJ, params);
    original = std::make_shared<Matter>(pot, params);
    original->con2matter(std::string("reactant.con"));
  }

  ~ConFileIOFixture() {
    // Clean up test output files
    std::remove("_test_roundtrip.con");
    std::remove("_test_append.con");
  }
};

TEST_CASE_METHOD(ConFileIOFixture,
                 "Con file write-read round trip preserves data",
                 "[confileio]") {
  std::string tmpfile = "_test_roundtrip.con";
  original->matter2con(tmpfile);

  auto loaded = std::make_shared<Matter>(pot, params);
  loaded->con2matter(tmpfile);

  REQUIRE(loaded->numberOfAtoms() == original->numberOfAtoms());

  // Positions match
  auto origPos = original->getPositions();
  auto loadPos = loaded->getPositions();
  REQUIRE(origPos.isApprox(loadPos, 1e-6));

  // Cell matches
  auto origCell = original->getCell();
  auto loadCell = loaded->getCell();
  REQUIRE(origCell.isApprox(loadCell, 1e-6));

  // Atomic numbers match
  REQUIRE(loaded->getAtomicNrs() == original->getAtomicNrs());
}

TEST_CASE_METHOD(ConFileIOFixture, "Con file append mode creates larger file",
                 "[confileio]") {
  std::string tmpfile = "_test_append.con";
  original->matter2con(tmpfile, false);

  // Get file size after first write
  auto size1 = std::filesystem::file_size(tmpfile);
  REQUIRE(size1 > 0);

  // Append a second structure
  original->matter2con(tmpfile, true);

  auto size2 = std::filesystem::file_size(tmpfile);
  REQUIRE(size2 > size1);
}

TEST_CASE_METHOD(
    ConFileIOFixture,
    "Metadata-rich append movies remain parseable with blank headers",
    "[confileio][append][metadata]") {
  std::string tmpfile = "_test_append_metadata.con";
  auto movie = std::make_shared<Matter>(pot, params);
  movie->resize(1);
  movie->setCell(10.0 * Matrix3d::Identity());
  movie->setPosition(0, 0, 0.0);
  movie->setPosition(0, 1, 0.0);
  movie->setPosition(0, 2, 0.0);
  movie->setMass(0, 1.0);
  movie->setAtomicNr(0, 1);
  movie->setFixed(0, false);

  eonc::io::ConFrameMetadata first;
  first.frame_index = 0;
  first.energy = -1.0;
  first.scalars.push_back({"step_size", 0.0});
  first.scalars.push_back({"convergence", 1.0});

  eonc::io::ConFrameMetadata second;
  second.frame_index = 1;
  second.energy = -2.0;
  second.scalars.push_back({"step_size", 0.1});
  second.scalars.push_back({"convergence", 0.5});

  REQUIRE(movie->matter2con(tmpfile, false, &first));
  REQUIRE(movie->matter2con(tmpfile, true, &second));

  std::ifstream file(tmpfile);
  std::string file_contents((std::istreambuf_iterator<char>(file)),
                            std::istreambuf_iterator<char>());
  REQUIRE_FALSE(file_contents.empty());
  REQUIRE(file_contents.front() != '\n');
  REQUIRE(file_contents.find("\"frame_index\":0") != std::string::npos);
  REQUIRE(file_contents.find("\"frame_index\":1") != std::string::npos);
  REQUIRE(file_contents.find("\"step_size\":0.1") != std::string::npos);

  const auto frames = readcon::read_all_frames(tmpfile);
  REQUIRE(frames.size() == 2);
  REQUIRE(frames[0].prebox_header()[0] == "Generated by eOn");
  REQUIRE(frames[1].prebox_header()[0] == "Generated by eOn");

  std::filesystem::remove(tmpfile);
}

TEST_CASE_METHOD(ConFileIOFixture,
                 "Con file free-function interface matches member delegates",
                 "[confileio]") {
  std::string tmpfile = "_test_roundtrip.con";
  eonc::io::matter2con(*original, tmpfile, false);

  auto loaded = std::make_shared<Matter>(pot, params);
  eonc::io::con2matter(*loaded, tmpfile);

  REQUIRE(loaded->numberOfAtoms() == original->numberOfAtoms());
  REQUIRE(loaded->getPositions().isApprox(original->getPositions(), 1e-6));
}

TEST_CASE_METHOD(ConFileIOFixture, "Con file preserves fixed-atom flags",
                 "[confileio]") {
  // Set some atoms as fixed
  original->setFixed(0, true);
  original->setFixed(1, false);

  std::string tmpfile = "_test_roundtrip.con";
  original->matter2con(tmpfile);

  auto loaded = std::make_shared<Matter>(pot, params);
  loaded->con2matter(tmpfile);

  REQUIRE(loaded->getFixed(0) == true);
  REQUIRE(loaded->getFixed(1) == false);
}

TEST_CASE_METHOD(ConFileIOFixture, "XYZ output is finite and non-empty",
                 "[confileio]") {
  // Note: matter2xyz appends ".xyz" to the filename
  auto tmppath = std::filesystem::temp_directory_path() / "_test_output";
  std::string tmpbase = tmppath.string();
  eonc::io::matter2xyz(*original, tmpbase);
  std::string tmpfile = tmpbase + ".xyz";

  auto size = std::filesystem::file_size(tmpfile);
  REQUIRE(size > 0);

  // Read first line -- should be atom count
  std::ifstream f(tmpfile);
  int natoms;
  f >> natoms;
  REQUIRE(natoms == original->numberOfAtoms());

  std::remove(tmpfile.c_str());
}

TEST_CASE_METHOD(ConFileIOFixture,
                 "String interface write-read roundtrip preserves geometry",
                 "[confileio]") {
  // Write via string interface
  eonc::io::matter2con(*original, "_test_str.con");

  // Read back
  auto loaded = std::make_shared<Matter>(pot, params);
  loaded->con2matter(std::string("_test_str.con"));

  REQUIRE(loaded->numberOfAtoms() == original->numberOfAtoms());
  REQUIRE(loaded->getPositions().isApprox(original->getPositions(), 1e-6));

  std::remove("_test_str.con");
}

TEST_CASE_METHOD(ConFileIOFixture,
                 "Con file energy is preserved after write-read cycle",
                 "[confileio]") {
  double E_orig = original->getPotentialEnergy();

  std::string tmpfile = "_test_roundtrip.con";
  original->matter2con(tmpfile);

  auto loaded = std::make_shared<Matter>(pot, params);
  loaded->con2matter(tmpfile);

  double E_loaded = loaded->getPotentialEnergy();
  // SVN reference: -39.965351
  REQUIRE(E_loaded == Catch::Approx(E_orig).epsilon(1e-6));
}

TEST_CASE("ConFileIO handles velocity data", "[confileio][velocity]") {
  Parameters params;
  params.potential_options.potential = PotType::LJ;
  auto pot = eonc::helpers::makePotential(PotType::LJ, params);
  auto m = std::make_shared<Matter>(pot, params);
  m->con2matter(std::string("reactant.con"));

  // Set some velocities
  auto vel = m->getVelocities();
  vel.setRandom();
  m->setVelocities(vel);

  // Write and read back
  auto tmppath = std::filesystem::temp_directory_path() / "_test_vel";
  std::string tmpfile = tmppath.string() + ".con";
  m->matter2con(tmpfile, false);

  auto m2 = std::make_shared<Matter>(pot, params);
  m2->con2matter(tmpfile);

  // Positions should match
  REQUIRE(m->getPositions().isApprox(m2->getPositions(), 1e-6));
  std::filesystem::remove(tmpfile);
}

TEST_CASE("ConFileIO multiple writes accumulate in append mode",
          "[confileio][append]") {
  Parameters params;
  params.potential_options.potential = PotType::LJ;
  auto pot = eonc::helpers::makePotential(PotType::LJ, params);
  auto m = std::make_shared<Matter>(pot, params);
  m->con2matter(std::string("reactant.con"));

  auto tmppath = std::filesystem::temp_directory_path() / "_test_append.con";
  std::string tmpfile = tmppath.string();

  // Write twice in append mode
  m->matter2con(tmpfile, false);
  m->matter2con(tmpfile, true);

  // File should be roughly double the size of single write
  auto fsize = std::filesystem::file_size(tmpfile);
  REQUIRE(fsize > 1000); // Two structures

  std::filesystem::remove(tmpfile);
}

TEST_CASE("ConFileIO embeds movie metadata in frame JSON",
          "[confileio][metadata]") {
  Parameters params;
  params.potential_options.potential = PotType::LJ;
  auto pot = eonc::helpers::makePotential(PotType::LJ, params);
  auto m = std::make_shared<Matter>(pot, params);
  m->con2matter(std::string("reactant.con"));
  m->setComputedPotential(-12.5, 0.0);

  eonc::io::ConFrameMetadata metadata;
  metadata.frame_index = 7;
  metadata.energy = -12.5;
  metadata.scalars.push_back({"step_size", 0.125});
  metadata.scalars.push_back({"convergence", 1.0e-3});

  auto tmppath = std::filesystem::temp_directory_path() / "_test_metadata.con";
  std::string tmpfile = tmppath.string();
  m->matter2con(tmpfile, false, &metadata);

  std::ifstream in(tmpfile);
  std::string file_contents((std::istreambuf_iterator<char>(in)),
                            std::istreambuf_iterator<char>());
  REQUIRE(file_contents.find("\"frame_index\":7") != std::string::npos);
  REQUIRE(file_contents.find("\"energy\":-12.5") != std::string::npos);
  REQUIRE(file_contents.find("\"step_size\":0.125") != std::string::npos);
  REQUIRE(file_contents.find("\"convergence\":0.001") != std::string::npos);

  std::filesystem::remove(tmpfile);
}

TEST_CASE("ConFileIO preserves metadata across append-mode movie frames",
          "[confileio][append][metadata]") {
  Parameters params;
  params.potential_options.potential = PotType::LJ;
  auto pot = eonc::helpers::makePotential(PotType::LJ, params);
  auto m = std::make_shared<Matter>(pot, params);
  m->resize(1);
  m->setCell(10.0 * Matrix3d::Identity());
  m->setAtomicNr(0, 1);
  m->setMass(0, 1.008);
  m->setPosition(0, 0, 1.0);
  m->setPosition(0, 1, 2.0);
  m->setPosition(0, 2, 3.0);
  m->setFixed(0, 0);

  auto tmppath =
      std::filesystem::temp_directory_path() / "_test_append_metadata.con";
  std::string tmpfile = tmppath.string();

  eonc::io::ConFrameMetadata first;
  first.frame_index = 0;
  first.energy = -10.0;
  first.scalars.push_back({"step_size", 0.0});
  REQUIRE(m->matter2con(tmpfile, false, &first));

  eonc::io::ConFrameMetadata second;
  second.frame_index = 1;
  second.energy = -9.5;
  second.scalars.push_back({"step_size", 0.25});
  REQUIRE(m->matter2con(tmpfile, true, &second));

  std::ifstream in(tmpfile);
  std::string file_contents((std::istreambuf_iterator<char>(in)),
                            std::istreambuf_iterator<char>());
  REQUIRE(file_contents.find("\"frame_index\":0") != std::string::npos);
  REQUIRE(file_contents.find("\"frame_index\":1") != std::string::npos);
  REQUIRE(file_contents.find("\"step_size\":0.25") != std::string::npos);
  REQUIRE(!file_contents.empty());
  REQUIRE(file_contents.front() != '\n');

  const auto frames = readcon::read_all_frames(tmpfile);
  REQUIRE(frames.size() == 2);
  REQUIRE(!frames[0].prebox_header()[0].empty());
  REQUIRE(!frames[1].prebox_header()[0].empty());
  REQUIRE(frames[0].prebox_header()[0] == "Generated by eOn");
  REQUIRE(frames[1].prebox_header()[0] == "Generated by eOn");

  std::filesystem::remove(tmpfile);
}

TEST_CASE("ConFileIO append mode rejects corrupt existing files",
          "[confileio][append][errors]") {
  Parameters params;
  params.potential_options.potential = PotType::LJ;
  auto pot = eonc::helpers::makePotential(PotType::LJ, params);
  auto m = std::make_shared<Matter>(pot, params);
  m->con2matter(std::string("reactant.con"));

  auto tmppath =
      std::filesystem::temp_directory_path() / "_test_corrupt_append.con";
  std::string tmpfile = tmppath.string();
  {
    std::ofstream out(tmpfile);
    out << "not a valid con file\n";
  }

  std::ifstream before_in(tmpfile);
  std::string before((std::istreambuf_iterator<char>(before_in)),
                     std::istreambuf_iterator<char>());

  REQUIRE_FALSE(m->matter2con(tmpfile, true));

  std::ifstream after_in(tmpfile);
  std::string after((std::istreambuf_iterator<char>(after_in)),
                    std::istreambuf_iterator<char>());
  REQUIRE(after == before);

  std::filesystem::remove(tmpfile);
}

TEST_CASE("ConFileIO appends .con based on basename extension",
          "[confileio][paths]") {
  Parameters params;
  params.potential_options.potential = PotType::LJ;
  auto pot = eonc::helpers::makePotential(PotType::LJ, params);
  auto m = std::make_shared<Matter>(pot, params);
  m->con2matter(std::string("reactant.con"));

  auto tmpdir = std::filesystem::temp_directory_path() / "nested.con.dir";
  std::filesystem::create_directories(tmpdir);
  auto tmpbase = tmpdir / "movie";

  REQUIRE(m->matter2con(tmpbase.string(), false));
  REQUIRE(std::filesystem::exists(tmpbase.string() + ".con"));
  REQUIRE_FALSE(std::filesystem::exists(tmpbase));

  std::filesystem::remove_all(tmpdir);
}

TEST_CASE("NEB path writer embeds structured frame metadata",
          "[confileio][neb][metadata]") {
  Parameters params;
  params.potential_options.potential = PotType::LJ;
  auto pot = eonc::helpers::makePotential(PotType::LJ, params);

  auto make_matter = [&]() {
    auto m = std::make_shared<Matter>(pot, params);
    m->con2matter(std::string("reactant.con"));
    return m;
  };

  std::vector<std::shared_ptr<Matter>> path{make_matter(), make_matter(),
                                            make_matter()};
  auto pos1 = path[1]->getPositions();
  pos1(0, 0) += 0.1;
  path[1]->setPositions(pos1);
  auto pos2 = path[2]->getPositions();
  pos2(0, 0) += 0.2;
  path[2]->setPositions(pos2);
  path[0]->setComputedPotential(-10.0, 0.0);
  path[1]->setComputedPotential(-9.5, 0.0);
  path[2]->setComputedPotential(-9.0, 0.0);

  std::vector<std::shared_ptr<AtomMatrix>> tangent(3);
  for (auto &t : tangent) {
    t = std::make_shared<AtomMatrix>();
    t->resize(path[0]->numberOfAtoms(), 3);
    t->setZero();
    (*t)(0, 0) = 1.0;
  }

  std::vector<std::shared_ptr<EigenmodeStrategy>> eigenmode_solvers(3);

  auto tmppath =
      std::filesystem::temp_directory_path() / "_test_neb_metadata.con";
  std::string tmpfile = tmppath.string();

  REQUIRE(eonc::neb::writePathCon(path, tangent, eigenmode_solvers, 1, false,
                                  tmpfile, 12));

  std::ifstream in(tmpfile);
  std::string file_contents((std::istreambuf_iterator<char>(in)),
                            std::istreambuf_iterator<char>());
  REQUIRE(file_contents.find("\"neb_band\":12") != std::string::npos);
  REQUIRE(file_contents.find("\"neb_bead\":1") != std::string::npos);
  REQUIRE(file_contents.find("\"reaction_coordinate\"") != std::string::npos);
  REQUIRE(file_contents.find("\"parallel_force\"") != std::string::npos);

  std::filesystem::remove(tmpfile);
}

TEST_CASE("ConFileIO reads multi-component Pt system",
          "[confileio][multicomponent]") {
  Parameters params;
  params.potential_options.potential = PotType::MORSE_PT;
  auto pot = eonc::helpers::makePotential(PotType::MORSE_PT, params);
  auto m = std::make_shared<Matter>(pot, params);
  m->con2matter(std::string("../Pt_Heptamer_FrozenLayers/pos.con"));

  // Pt heptamer has atoms with some fixed
  REQUIRE(m->numberOfAtoms() > 0);
  REQUIRE(m->numberOfFreeAtoms() < m->numberOfAtoms());

  // Verify cell is reasonable
  auto cell = m->getCell();
  REQUIRE(cell(0, 0) > 0.0);
  REQUIRE(cell(1, 1) > 0.0);
  REQUIRE(cell(2, 2) > 0.0);

  // Write and read back
  auto tmppath = std::filesystem::temp_directory_path() / "_test_multi.con";
  std::string tmpfile = tmppath.string();
  m->matter2con(tmpfile, false);

  auto m2 = std::make_shared<Matter>(pot, params);
  m2->con2matter(tmpfile);

  REQUIRE(m2->numberOfAtoms() == m->numberOfAtoms());
  REQUIRE(m2->numberOfFreeAtoms() == m->numberOfFreeAtoms());
  REQUIRE(m->getPositions().isApprox(m2->getPositions(), 1e-6));

  std::filesystem::remove(tmpfile);
}

TEST_CASE("ConFileIO reads Si diamond system", "[confileio][si]") {
  Parameters params;
  params.potential_options.potential = PotType::SW_SI;
  auto pot = eonc::helpers::makePotential(PotType::SW_SI, params);
  auto m = std::make_shared<Matter>(pot, params);
  m->con2matter(std::string("../si_diamond/pos.con"));

  REQUIRE(m->numberOfAtoms() == 8);
  REQUIRE(m->getAtomicNr(0) == 14); // Si atomic number
}

TEST_CASE("ConFileIO convel round-trip preserves velocities",
          "[confileio][convel]") {
  Parameters params;
  params.potential_options.potential = PotType::LJ;
  auto pot = eonc::helpers::makePotential(PotType::LJ, params);
  auto m = std::make_shared<Matter>(pot, params);
  m->con2matter(std::string("reactant.con"));

  // Set velocities
  auto vel = m->getVelocities();
  vel.setRandom();
  vel *= 0.01; // small velocities
  m->setVelocities(vel);

  auto tmppath = std::filesystem::temp_directory_path() / "_test_out.convel";
  std::string tmpfile = tmppath.string();

  // Write convel (function expects .convel extension or appends it)
  eonc::io::matter2convel(*m, tmpfile);
  REQUIRE(std::filesystem::exists(tmpfile));

  // Read back
  auto m2 = std::make_shared<Matter>(pot, params);
  eonc::io::convel2matter(*m2, tmpfile);

  // Positions and velocities should match
  REQUIRE(m->getPositions().isApprox(m2->getPositions(), 1e-6));
  auto vel2 = m2->getVelocities();
  // convel format has limited precision
  REQUIRE(vel.isApprox(vel2, 1e-3));

  std::filesystem::remove(tmpfile);
}

TEST_CASE("ConFileIO writeTibble produces valid output",
          "[confileio][tibble]") {
  Parameters params;
  params.potential_options.potential = PotType::LJ;
  auto pot = eonc::helpers::makePotential(PotType::LJ, params);
  auto m = std::make_shared<Matter>(pot, params);
  m->con2matter(std::string("reactant.con"));
  // Trigger force computation so writeTibble can access forces
  m->getPotentialEnergy();

  auto tmppath = std::filesystem::temp_directory_path() / "_test_tibble.dat";
  std::string tmpfile = tmppath.string();

  eonc::io::writeTibble(*m, tmpfile);
  REQUIRE(std::filesystem::exists(tmpfile));
  auto fsize = std::filesystem::file_size(tmpfile);
  REQUIRE(fsize > 50);

  std::filesystem::remove(tmpfile);
}

} /* namespace tests */
