/*
** This file is part of eOn.
**
** SPDX-License-Identifier: BSD-3-Clause
**
** Copyright (c) 2010--present, eOn Development Team
** All rights reserved.
**
** Repo:
** https://github.com/TheochemUI/eOn
*/

#include "TestUtils.hpp"
#include "catch2/catch_amalgamated.hpp"
#include "eon/IDPPObjectiveFunction.hpp"
#include "eon/NEBInitialPaths.hpp"
#include "eon/NEBOcinebController.h"
#include "eon/NudgedElasticBand.h"
#include "eon/PotCapabilities.h"
#include "eon/PotRegistry.h"
#include "eon/api.h"
#include <fstream>
#include <stdexcept>
#include <thread>
#include <vector>

namespace tests {

static eonc::helpers::test::QuillTestLogger _quill_setup;

/// Fixture using LJ potential on a 13-atom cluster.
/// Product is generated by displacing one atom from the reactant geometry.
class NEBLJFixture {
protected:
  Parameters params;
  std::shared_ptr<Potential> pot;
  std::shared_ptr<Matter> reactant;
  std::shared_ptr<Matter> product;

  NEBLJFixture()
      : params{},
        pot{nullptr},
        reactant{nullptr},
        product{nullptr} {
    ParametersLoadAccess::potential_options(params).potential = PotType::LJ;
    pot = eonc::helpers::makePotential(PotType::LJ, params);
    reactant = std::make_shared<Matter>(pot, params);
    product = std::make_shared<Matter>(pot, params);

    reactant->con2matter(std::string("reactant.con"));
    // Create product by displacing atom 0 slightly
    product->con2matter(std::string("reactant.con"));
    auto pos = product->getPositions();
    pos(0, 0) += 0.5;
    pos(0, 1) -= 0.3;
    pos(0, 2) += 0.2;
    product->setPositions(pos);

    ParametersLoadAccess::optimizer_options(params).max_iterations = 500;
    ParametersLoadAccess::optimizer_options(params).method = OptType::LBFGS;
    ParametersLoadAccess::optimizer_options(params).max_move = 0.2;
    ParametersLoadAccess::neb_options(params).image_count = 5;
    ParametersLoadAccess::neb_options(params).force_tolerance = 0.01;
    ParametersLoadAccess::neb_options(params).initialization.method =
        NEBInit::LINEAR;
    ParametersLoadAccess::neb_options(params).endpoints.minimize = false;
    ParametersLoadAccess::neb_options(params).climbing_image.enabled = false;
  }

  auto makeNEB() {
    return std::make_unique<NudgedElasticBand>(reactant, product, params, pot);
  }
};

// --- Construction tests ---

TEST_CASE_METHOD(NEBLJFixture, "NEB path constructor rejects a short path",
                 "[neb][construction][lk6g]") {
  std::vector<Matter> shortPath{*reactant, *product};
  REQUIRE_THROWS_AS(NudgedElasticBand(shortPath, params, pot),
                    std::invalid_argument);
}

TEST_CASE_METHOD(NEBLJFixture, "NEB construction and basic state",
                 "[neb][construction]") {
  auto neb = makeNEB();

  REQUIRE(neb->atoms == reactant->numberOfAtoms());
  REQUIRE(neb->numImages == 5);
  REQUIRE(neb->path.size() == static_cast<size_t>(neb->numImages + 2));
  REQUIRE(neb->movedAfterForceCall == true);
  REQUIRE(neb->tangent.size() == neb->path.size());
  REQUIRE(neb->projectedForce.size() == neb->path.size());
}

TEST_CASE_METHOD(NEBLJFixture,
                 "NEB rejects reactant/product atom count mismatch",
                 "[neb][construction][issue540]") {
  REQUIRE(product->numberOfAtoms() > 1);
  product->resize(product->numberOfAtoms() - 1);
  REQUIRE_THROWS_WITH(makeNEB(), Catch::Matchers::ContainsSubstring(
                                     "do not have the same number of atoms"));
  REQUIRE_THROWS_AS(
      eonc::helpers::neb_paths::linearPath(*reactant, *product, 5),
      std::invalid_argument);
}

TEST_CASE_METHOD(NEBLJFixture, "NEB endpoints match input structures",
                 "[neb][construction]") {
  auto neb = makeNEB();

  auto reactPos = reactant->getPositions();
  auto firstPos = neb->path[0]->getPositions();
  REQUIRE(reactPos.isApprox(firstPos, 1e-10));

  auto prodPos = product->getPositions();
  auto lastPos = neb->path[neb->numImages + 1]->getPositions();
  REQUIRE(prodPos.isApprox(lastPos, 1e-10));
}

// --- Linear interpolation tests ---

TEST_CASE_METHOD(NEBLJFixture, "Linear path interpolation is evenly spaced",
                 "[neb][linear_init]") {
  auto neb = makeNEB();

  auto reactPos = neb->path[0]->getPositions();
  auto prodPos = neb->path[neb->numImages + 1]->getPositions();

  for (long i = 1; i <= neb->numImages; i++) {
    double frac = static_cast<double>(i) / (neb->numImages + 1);
    AtomMatrix expected = reactPos + frac * (prodPos - reactPos);
    auto imgPos = neb->path[i]->getPositions();
    REQUIRE(imgPos.isApprox(expected, 1e-6));
  }
}

// --- Force update tests ---

TEST_CASE_METHOD(NEBLJFixture, "updateForces computes tangents and forces",
                 "[neb][updateForces]") {
  auto neb = makeNEB();
  neb->updateForces();

  REQUIRE(neb->movedAfterForceCall == false);

  for (long i = 1; i <= neb->numImages; i++) {
    double tnorm = neb->tangent[i]->norm();
    REQUIRE_THAT(tnorm, Catch::Matchers::WithinAbs(1.0, 1e-10));
  }

  double maxForce = 0.0;
  for (long i = 1; i <= neb->numImages; i++) {
    double fnorm = neb->projectedForce[i]->norm();
    maxForce = std::max(maxForce, fnorm);
  }
  REQUIRE(maxForce > 0.0);

  REQUIRE(neb->maxEnergyImage >= 1);
  REQUIRE(neb->maxEnergyImage <= static_cast<size_t>(neb->numImages));
}

// --- Convergence force metric tests ---

TEST_CASE_METHOD(NEBLJFixture, "convergenceForce norm metric",
                 "[neb][convergenceForce][norm]") {
  ParametersLoadAccess::optimizer_options(params).convergence_metric = "norm";
  auto neb = makeNEB();
  neb->updateForces();

  double cf = neb->convergenceForce();
  REQUIRE(cf > 0.0);
  REQUIRE(std::isfinite(cf));
}

TEST_CASE_METHOD(NEBLJFixture, "convergenceForce max_atom metric",
                 "[neb][convergenceForce][max_atom]") {
  ParametersLoadAccess::optimizer_options(params).convergence_metric =
      "max_atom";
  auto neb = makeNEB();
  neb->updateForces();

  double cf = neb->convergenceForce();
  REQUIRE(cf > 0.0);
  REQUIRE(std::isfinite(cf));
}

TEST_CASE_METHOD(NEBLJFixture, "convergenceForce max_component metric",
                 "[neb][convergenceForce][max_component]") {
  ParametersLoadAccess::optimizer_options(params).convergence_metric =
      "max_component";
  auto neb = makeNEB();
  neb->updateForces();

  double cf = neb->convergenceForce();
  REQUIRE(cf > 0.0);
  REQUIRE(std::isfinite(cf));
}

// --- Spring force tests ---

TEST_CASE_METHOD(NEBLJFixture, "Uniform spring forces",
                 "[neb][spring_uniform]") {
  ParametersLoadAccess::neb_options(params).spring.weighting.enabled = false;
  ParametersLoadAccess::neb_options(params).spring.constant = 5.0;
  auto neb = makeNEB();
  neb->updateForces();

  REQUIRE_THAT(neb->ksp, Catch::Matchers::WithinAbs(5.0, 1e-10));

  for (long i = 1; i <= neb->numImages; i++) {
    REQUIRE(neb->projectedForce[i]->norm() > 0.0);
  }
}

TEST_CASE_METHOD(NEBLJFixture, "Energy-weighted springs differ from uniform",
                 "[neb][spring_energy_weighted]") {
  ParametersLoadAccess::neb_options(params).spring.weighting.enabled = false;
  ParametersLoadAccess::neb_options(params).spring.constant = 5.0;
  auto neb_uniform = makeNEB();
  neb_uniform->updateForces();

  std::vector<double> uniform_norms;
  for (long i = 1; i <= neb_uniform->numImages; i++) {
    uniform_norms.push_back(neb_uniform->projectedForce[i]->norm());
  }

  ParametersLoadAccess::neb_options(params).spring.weighting.enabled = true;
  ParametersLoadAccess::neb_options(params).spring.weighting.k_min = 1.0;
  ParametersLoadAccess::neb_options(params).spring.weighting.k_max = 10.0;
  auto neb_weighted = makeNEB();
  neb_weighted->updateForces();

  bool any_differ = false;
  for (long i = 1; i <= neb_weighted->numImages; i++) {
    double wn = neb_weighted->projectedForce[i]->norm();
    if (std::abs(wn - uniform_norms[i - 1]) > 1e-6) {
      any_differ = true;
      break;
    }
  }
  REQUIRE(any_differ);
}

TEST_CASE_METHOD(NEBLJFixture, "Doubly nudged elastic band springs",
                 "[neb][spring_doubly_nudged]") {
  ParametersLoadAccess::neb_options(params).spring.doubly_nudged = true;
  ParametersLoadAccess::neb_options(params).spring.constant = 5.0;
  auto neb = makeNEB();
  neb->updateForces();

  for (long i = 1; i <= neb->numImages; i++) {
    REQUIRE(neb->projectedForce[i]->allFinite());
  }
}

TEST_CASE_METHOD(NEBLJFixture, "Old tangent scheme produces valid tangents",
                 "[neb][tangent_old]") {
  ParametersLoadAccess::neb_options(params).climbing_image.use_old_tangent =
      true;
  auto neb = makeNEB();
  neb->updateForces();

  for (long i = 1; i <= neb->numImages; i++) {
    double tnorm = neb->tangent[i]->norm();
    REQUIRE_THAT(tnorm, Catch::Matchers::WithinAbs(1.0, 1e-10));
  }
}

TEST_CASE_METHOD(NEBLJFixture, "Elastic band spring forces",
                 "[neb][spring_elastic_band]") {
  ParametersLoadAccess::neb_options(params).spring.use_elastic_band = true;
  ParametersLoadAccess::neb_options(params).spring.constant = 5.0;
  auto neb = makeNEB();
  neb->updateForces();

  for (long i = 1; i <= neb->numImages; i++) {
    REQUIRE(neb->projectedForce[i]->allFinite());
    REQUIRE(neb->projectedForce[i]->norm() > 0.0);
  }
}

// --- Climbing image tests ---

TEST_CASE_METHOD(NEBLJFixture, "Climbing image activation",
                 "[neb][climbing_image]") {
  ParametersLoadAccess::neb_options(params).climbing_image.enabled = true;
  ParametersLoadAccess::neb_options(params).climbing_image.trigger_force = 1e10;
  ParametersLoadAccess::neb_options(params).climbing_image.trigger_factor = 1.0;
  ParametersLoadAccess::optimizer_options(params).max_iterations = 500;
  ParametersLoadAccess::neb_options(params).force_tolerance = 0.05;

  auto neb = makeNEB();
  neb->compute();

  REQUIRE(neb->climbingImage >= 0);
}

// --- Full convergence tests ---

TEST_CASE_METHOD(NEBLJFixture, "NEB converges with LJ potential",
                 "[neb][compute]") {
  ParametersLoadAccess::optimizer_options(params).max_iterations = 5000;
  ParametersLoadAccess::neb_options(params).force_tolerance = 0.05;

  auto neb = makeNEB();
  auto status = neb->compute();

  REQUIRE(static_cast<int>(status) ==
          static_cast<int>(NudgedElasticBand::NEBStatus::GOOD));
  REQUIRE(neb->convergenceForce() <
          ParametersLoadAccess::neb_options(params).force_tolerance);
}

TEST_CASE_METHOD(NEBLJFixture, "NEB respects max iterations",
                 "[neb][compute_max_iter]") {
  // Use a large displacement so convergence is impossible in 2 steps
  auto pos = product->getPositions();
  pos(0, 0) += 3.0;
  pos(0, 1) -= 2.0;
  pos(0, 2) += 2.5;
  product->setPositions(pos);

  ParametersLoadAccess::optimizer_options(params).max_iterations = 1;
  ParametersLoadAccess::neb_options(params).force_tolerance = 1e-15;

  auto neb = makeNEB();
  auto status = neb->compute();

  REQUIRE(static_cast<int>(status) ==
          static_cast<int>(NudgedElasticBand::NEBStatus::BAD_MAX_ITERATIONS));
}

// --- Extrema detection tests ---

TEST_CASE_METHOD(NEBLJFixture, "findExtrema identifies extrema",
                 "[neb][findExtrema]") {
  ParametersLoadAccess::optimizer_options(params).max_iterations = 5000;
  ParametersLoadAccess::neb_options(params).force_tolerance = 0.05;

  auto neb = makeNEB();
  auto status = neb->compute();

  if (status == NudgedElasticBand::NEBStatus::GOOD) {
    neb->findExtrema();
    REQUIRE(neb->numExtrema >= 1);

    for (long j = 0; j < neb->numExtrema; j++) {
      REQUIRE(std::isfinite(neb->extremumEnergy[j]));
      REQUIRE(neb->extremumPosition[j] >= 0.0);
      REQUIRE(neb->extremumPosition[j] <=
              static_cast<double>(neb->numImages + 1));
      REQUIRE(std::isfinite(neb->extremumCurvature[j]));
    }
  }
}

// --- NEBObjectiveFunction tests ---

TEST_CASE_METHOD(NEBLJFixture, "NEBObjectiveFunction interface",
                 "[neb][objective_function]") {
  auto neb = makeNEB();
  NEBObjectiveFunction objFunc(neb.get(), params);

  SECTION("degreesOfFreedom") {
    REQUIRE(objFunc.degreesOfFreedom() == 3 * neb->atoms * neb->numImages);
  }

  SECTION("getPositions has correct size") {
    auto pos = objFunc.getPositions();
    REQUIRE(pos.size() == 3 * neb->atoms * neb->numImages);
  }

  SECTION("getGradient has correct size") {
    auto grad = objFunc.getGradient();
    REQUIRE(grad.size() == 3 * neb->atoms * neb->numImages);
  }

  SECTION("setPositions/getPositions round-trip") {
    auto original = objFunc.getPositions();
    VectorXd modified = original;
    modified(0) += 0.001;
    objFunc.setPositions(modified);
    auto retrieved = objFunc.getPositions();
    REQUIRE(modified.isApprox(retrieved, 1e-12));
  }

  SECTION("isConverged returns false for initial path") {
    REQUIRE(objFunc.isConverged() == false);
  }

  SECTION("getEnergy returns finite sum") {
    double energy = objFunc.getEnergy();
    REQUIRE(std::isfinite(energy));
  }

  SECTION("getConvergence returns positive value") {
    double conv = objFunc.getConvergence();
    REQUIRE(conv > 0.0);
    REQUIRE(std::isfinite(conv));
  }
}

// --- Edge case tests ---

TEST_CASE_METHOD(NEBLJFixture, "NEB with single image does not crash",
                 "[neb][single_image]") {
  ParametersLoadAccess::neb_options(params).image_count = 1;
  ParametersLoadAccess::optimizer_options(params).max_iterations = 10;

  auto neb = makeNEB();
  REQUIRE(neb->numImages == 1);
  REQUIRE(neb->path.size() == 3);

  auto status = neb->compute();
  REQUIRE((status == NudgedElasticBand::NEBStatus::GOOD ||
           status == NudgedElasticBand::NEBStatus::BAD_MAX_ITERATIONS));
}

// --- Potential thread safety tests ---

TEST_CASE("OCI-NEB shouldTrigger uses 2*ftol not trigger_force", "[neb][awc]") {
  Parameters p;
  ParametersLoadAccess::neb_options(p).force_tolerance = 0.01;
  ParametersLoadAccess::neb_options(p).climbing_image.ocineb.use_mmf = true;
  ParametersLoadAccess::neb_options(p).climbing_image.ocineb.trigger_factor =
      0.0;
  ParametersLoadAccess::neb_options(p).climbing_image.ocineb.trigger_force =
      100.0;
  ParametersLoadAccess::neb_options(p)
      .climbing_image.ocineb.ci_stability_count = 0;
  auto cfg = eonc::neb::OCINEBController::fromParams(p);
  eonc::neb::OCINEBController ctl(cfg);
  ctl.initBaseline(1.0);
  REQUIRE(ctl.threshold() == Catch::Approx(0.02).margin(1e-12));
  REQUIRE(ctl.shouldTrigger(0.015, true, 1, 5, 1));
  REQUIRE_FALSE(ctl.shouldTrigger(0.05, true, 1, 5, 1));
}

TEST_CASE("NEB match_endpoints is off by default", "[neb][srlq]") {
  Parameters params;
  REQUIRE_FALSE(ParametersLoadAccess::neb_options(params).match_endpoints);
  REQUIRE(ParametersLoadAccess::neb_options(params).match_method == "ira");
}

TEST_CASE("NEB writes MMF peak seeds by default", "[neb][xr04]") {
  Parameters params;
  REQUIRE(ParametersLoadAccess::neb_options(params).mmf_peaks.enabled);
  REQUIRE(ParametersLoadAccess::neb_options(params).mmf_peaks.tolerance ==
          Catch::Approx(0.05).margin(1e-12));
}

TEST_CASE("Potential isThreadSafe defaults to true",
          "[potential][thread_safety]") {
  Parameters params;
  auto pot = eonc::helpers::makePotential(PotType::LJ, params);
  REQUIRE(pot->isThreadSafe() == true);
  REQUIRE(pot->isSharedInstanceThreadSafe() == true);
  REQUIRE(eonc::potIsThreadSafe(*pot));
  REQUIRE(eonc::potAllowsSharedInstance(*pot));
}

TEST_CASE("Potential thread_safe=false forces serial sharing",
          "[potential][thread_safety][gjg]") {
  Parameters params;
  ParametersLoadAccess::potential_options(params).thread_safe = false;
  auto pot = eonc::helpers::makePotential(PotType::LJ, params);
  REQUIRE(pot->isThreadSafe() == true);
  REQUIRE(pot->isSharedInstanceThreadSafe() == false);
}

TEST_CASE("Potential forceCallCounter is atomic",
          "[potential][thread_safety]") {
  Parameters params;
  auto pot = eonc::helpers::makePotential(PotType::LJ, params);
  pot->forceCallCounter++;
  REQUIRE(pot->forceCallCounter.load() == 1);
  pot->forceCallCounter.store(42);
  REQUIRE(pot->forceCallCounter.load() == 42);
}

// --- Parallel bead force evaluation tests ---

TEST_CASE_METHOD(
    NEBLJFixture,
    "Concurrent force calls on independent images produce correct results",
    "[neb][parallel]") {
  auto neb = makeNEB();

  // Force-evaluate all images sequentially, record energies
  std::vector<double> seqEnergies(neb->numImages);
  for (long i = 1; i <= neb->numImages; i++) {
    neb->path[i]->getForces();
    seqEnergies[i - 1] = neb->path[i]->getPotentialEnergy();
  }

  // Reset all images and force-evaluate in parallel using std::thread
  for (long i = 1; i <= neb->numImages; i++) {
    // Perturb slightly to force re-evaluation
    auto pos = neb->path[i]->getPositions();
    pos(0, 0) += 1e-12;
    neb->path[i]->setPositions(pos);
  }

  std::vector<std::thread> threads;
  std::vector<double> parEnergies(neb->numImages);
  for (long i = 1; i <= neb->numImages; i++) {
    threads.emplace_back([&, i]() {
      neb->path[i]->getForces();
      parEnergies[i - 1] = neb->path[i]->getPotentialEnergy();
    });
  }
  for (auto &t : threads) {
    t.join();
  }

  // Energies should match (within numerical noise from 1e-12 perturbation)
  for (long i = 0; i < neb->numImages; i++) {
    REQUIRE_THAT(parEnergies[i],
                 Catch::Matchers::WithinAbs(seqEnergies[i], 1e-6));
  }
}

TEST_CASE("Concurrent potential force calls preserve atomic counter",
          "[potential][parallel]") {
  Parameters params;
  auto pot = eonc::helpers::makePotential(PotType::LJ, params);

  AtomMatrix pos(2, 3);
  pos << 0.0, 0.0, 0.0, 1.5, 0.0, 0.0;
  VectorXi atmnrs(2);
  atmnrs << 1, 1;
  Matrix3d box = Matrix3d::Identity() * 10.0;

  const int nThreads = 8;
  const int callsPerThread = 100;
  std::vector<std::thread> threads;

  for (int t = 0; t < nThreads; t++) {
    threads.emplace_back([&]() {
      for (int c = 0; c < callsPerThread; c++) {
        pot->get_ef(pos, atmnrs, box);
      }
    });
  }
  for (auto &t : threads) {
    t.join();
  }

  REQUIRE(pot->forceCallCounter.load() ==
          static_cast<size_t>(nThreads * callsPerThread));
  REQUIRE(PotRegistry::get().type_force_calls(PotType::LJ) >=
          static_cast<size_t>(nThreads * callsPerThread));
}

TEST_CASE_METHOD(NEBLJFixture,
                 "NEB produces same result with sequential force evaluation",
                 "[neb][parallel][regression]") {
  // Run NEB to convergence
  ParametersLoadAccess::optimizer_options(params).max_iterations = 5000;
  ParametersLoadAccess::neb_options(params).force_tolerance = 0.05;
  auto neb = makeNEB();
  auto status = neb->compute();

  if (status == NudgedElasticBand::NEBStatus::GOOD) {
    neb->findExtrema();
    double barrier =
        neb->extremumEnergy[0] - neb->path[0]->getPotentialEnergy();
    REQUIRE(std::isfinite(barrier));
    // The barrier should be positive (uphill from reactant)
    // or at least finite for a valid NEB result
    REQUIRE(neb->numExtrema >= 1);
  }
}

// --- PotRegistry regression ---

TEST_CASE("PotRegistry write_summary empty when potential alive",
          "[PotRegistry][json][regression]") {
  PotRegistry::get().reset();
  Parameters params;

  auto live_pot = eonc::helpers::makePotential(PotType::LJ, params);

  AtomMatrix pos(2, 3);
  pos << 0.0, 0.0, 0.0, 1.5, 0.0, 0.0;
  VectorXi atmnrs(2);
  atmnrs << 1, 1;
  Matrix3d box = Matrix3d::Identity() * 10.0;
  live_pot->get_ef(pos, atmnrs, box);

  // While alive: no records
  std::string path1 = "_test_potcalls_live.json";
  PotRegistry::get().write_summary(path1);
  std::ifstream ifs1(path1);
  std::string content1((std::istreambuf_iterator<char>(ifs1)),
                       std::istreambuf_iterator<char>());
  ifs1.close();
  std::remove(path1.c_str());
  REQUIRE(content1.find("\"force_calls\"") == std::string::npos);

  // After destroy: records present
  live_pot.reset();
  std::string path2 = "_test_potcalls_after_destroy.json";
  PotRegistry::get().write_summary(path2);
  std::ifstream ifs2(path2);
  std::string content2((std::istreambuf_iterator<char>(ifs2)),
                       std::istreambuf_iterator<char>());
  ifs2.close();
  std::remove(path2.c_str());
  REQUIRE(content2.find("\"force_calls\": 1") != std::string::npos);
}

// --- IDPP initialization tests ---

TEST_CASE_METHOD(NEBLJFixture, "IDPP initialization produces valid path",
                 "[neb][idpp]") {
  ParametersLoadAccess::neb_options(params).initialization.method =
      NEBInit::IDPP;
  ParametersLoadAccess::neb_options(params).initialization.max_iterations = 100;
  auto neb = makeNEB();

  // IDPP should produce a path different from linear interpolation
  auto reactPos = neb->path[0]->getPositions();
  auto prodPos = neb->path[neb->numImages + 1]->getPositions();

  // Endpoints should still match
  REQUIRE(reactPos.isApprox(reactant->getPositions(), 1e-10));
  REQUIRE(prodPos.isApprox(product->getPositions(), 1e-10));

  // Interior images should be valid (finite positions)
  for (long i = 1; i <= neb->numImages; i++) {
    auto imgPos = neb->path[i]->getPositions();
    REQUIRE(imgPos.allFinite());
  }
}

TEST_CASE_METHOD(NEBLJFixture, "IDPP path differs from linear interpolation",
                 "[neb][idpp]") {
  // Build linear path
  ParametersLoadAccess::neb_options(params).initialization.method =
      NEBInit::LINEAR;
  auto neb_lin = makeNEB();

  // Build IDPP path
  ParametersLoadAccess::neb_options(params).initialization.method =
      NEBInit::IDPP;
  ParametersLoadAccess::neb_options(params).initialization.max_iterations = 100;
  auto neb_idpp = makeNEB();

  // At least one interior image should differ from linear
  bool differs = false;
  for (long i = 1; i <= neb_lin->numImages; i++) {
    auto linPos = neb_lin->path[i]->getPositions();
    auto idppPos = neb_idpp->path[i]->getPositions();
    if (!linPos.isApprox(idppPos, 1e-6)) {
      differs = true;
      break;
    }
  }
  REQUIRE(differs);
}

// --- Climbing image tests ---

TEST_CASE_METHOD(NEBLJFixture, "NEB with climbing image enabled runs",
                 "[neb][climbing_image]") {
  ParametersLoadAccess::neb_options(params).climbing_image.enabled = true;
  ParametersLoadAccess::neb_options(params).climbing_image.converged_only =
      false;
  ParametersLoadAccess::neb_options(params).climbing_image.trigger_force = 0.0;
  auto neb = makeNEB();

  // Run a few iterations with climbing image
  auto status = neb->compute();

  // Should terminate (GOOD or BAD_MAX_ITERATIONS)
  REQUIRE((status == NudgedElasticBand::NEBStatus::GOOD ||
           status == NudgedElasticBand::NEBStatus::BAD_MAX_ITERATIONS));
}

TEST_CASE_METHOD(NEBLJFixture, "NEB compute converges or hits max iterations",
                 "[neb][compute]") {
  ParametersLoadAccess::optimizer_options(params).max_iterations = 50;
  ParametersLoadAccess::neb_options(params).force_tolerance = 0.01;
  auto neb = makeNEB();

  auto status = neb->compute();

  REQUIRE((status == NudgedElasticBand::NEBStatus::GOOD ||
           status == NudgedElasticBand::NEBStatus::BAD_MAX_ITERATIONS));
}

TEST_CASE_METHOD(NEBLJFixture, "converged_only does not ignore a hot band",
                 "[neb][converged_only][bghy]") {
  ParametersLoadAccess::neb_options(params).climbing_image.enabled = true;
  ParametersLoadAccess::neb_options(params).climbing_image.converged_only =
      true;
  ParametersLoadAccess::neb_options(params).climbing_image.band_slack = 10.0;
  ParametersLoadAccess::neb_options(params).force_tolerance = 0.01;
  auto neb = makeNEB();
  neb->updateForces();
  neb->setCIEnabled(true);
  neb->climbingImage = 1;
  REQUIRE(neb->convergenceForce() >
          10.0 * ParametersLoadAccess::neb_options(params).force_tolerance);
}

TEST_CASE_METHOD(NEBLJFixture, "SIDPP rejects a collapsed adjacent pair",
                 "[neb][sidpp][bghy]") {
  std::vector<Matter> path{*reactant, *reactant, *product};
  REQUIRE_THROWS_AS(
      eonc::helpers::neb_paths::ensureDistinctAdjacentImages(path, 1e-6),
      std::runtime_error);
}

TEST_CASE_METHOD(NEBLJFixture, "SIDPP initialization produces valid path",
                 "[neb][sidpp]") {
  ParametersLoadAccess::neb_options(params).initialization.method =
      NEBInit::SIDPP;
  ParametersLoadAccess::neb_options(params).initialization.max_iterations = 50;
  auto neb = makeNEB();

  auto reactPos = neb->path[0]->getPositions();
  auto prodPos = neb->path[neb->numImages + 1]->getPositions();
  REQUIRE(reactPos.isApprox(reactant->getPositions(), 1e-10));
  REQUIRE(prodPos.isApprox(product->getPositions(), 1e-10));

  for (long i = 1; i <= neb->numImages; i++) {
    REQUIRE(neb->path[i]->getPositions().allFinite());
  }
}

TEST_CASE_METHOD(NEBLJFixture, "IDPP collective initialization",
                 "[neb][idpp_collective]") {
  ParametersLoadAccess::neb_options(params).initialization.method =
      NEBInit::IDPP_COLLECTIVE;
  ParametersLoadAccess::neb_options(params).initialization.max_iterations = 50;
  auto neb = makeNEB();

  for (long i = 1; i <= neb->numImages; i++) {
    REQUIRE(neb->path[i]->getPositions().allFinite());
  }
}

TEST_CASE("Collective IDPP lastMaxForce ignores frozen atoms",
          "[neb][idpp_collective][lyqe]") {
  Parameters params;
  ParametersLoadAccess::potential_options(params).potential = PotType::LJ;
  ParametersLoadAccess::neb_options(params).spring.constant = 0.0;
  auto pot = eonc::helpers::makePotential(PotType::LJ, params);

  auto makeImage = [&](double xFree) {
    Matter m(pot, params);
    m.resize(3);
    m.setAtomicNr(0, 1);
    m.setAtomicNr(1, 1);
    m.setAtomicNr(2, 1);
    AtomMatrix p(3, 3);
    p << xFree, 0.0, 0.0, -2.0, 0.0, 0.0, 10.0, 0.0, 0.0;
    m.setPositions(p);
    m.setCell(Matrix3d::Identity() * 40.0);
    m.setPeriodic(false);
    m.setFixed(1, true);
    m.setFixed(2, true);
    return m;
  };

  // Midpoint is not the linear interpolation of the free atom, so the
  // two frozen neighbours carry large uncancelled pair residuals.
  Matter reactant = makeImage(0.0);
  Matter mid = makeImage(0.5);
  Matter product = makeImage(4.0);
  std::vector<Matter> path{reactant, mid, product};
  CollectiveIDPPObjectiveFunction of(path, params);
  VectorXd g = of.getGradient();
  REQUIRE(g.size() == 3);
  REQUIRE(of.getConvergence() ==
          Catch::Approx(g.lpNorm<Eigen::Infinity>()).margin(1e-12));
}

TEST_CASE_METHOD(NEBLJFixture, "NEB with OCINEB hybrid dimer",
                 "[neb][ocineb]") {
  ParametersLoadAccess::neb_options(params).climbing_image.enabled = true;
  ParametersLoadAccess::neb_options(params).climbing_image.converged_only =
      false;
  ParametersLoadAccess::neb_options(params).climbing_image.trigger_force = 0.0;
  ParametersLoadAccess::neb_options(params).climbing_image.ocineb.use_mmf =
      true;
  ParametersLoadAccess::neb_options(params)
      .climbing_image.ocineb.trigger_factor = 100.0;
  ParametersLoadAccess::neb_options(params).climbing_image.ocineb.max_steps = 5;
  ParametersLoadAccess::optimizer_options(params).max_iterations = 20;
  ParametersLoadAccess::neb_options(params).force_tolerance = 0.1;

  auto neb = makeNEB();
  auto status = neb->compute();

  REQUIRE((status == NudgedElasticBand::NEBStatus::GOOD ||
           status == NudgedElasticBand::NEBStatus::BAD_MAX_ITERATIONS));
}

TEST_CASE_METHOD(NEBLJFixture, "NEB spring switching",
                 "[neb][spring_switching]") {
  ParametersLoadAccess::neb_options(params).spring.use_switching = true;
  ParametersLoadAccess::neb_options(params).spring.constant = 5.0;
  auto neb = makeNEB();
  neb->updateForces();

  for (long i = 1; i <= neb->numImages; i++) {
    REQUIRE(neb->projectedForce[i]->allFinite());
  }
}

TEST_CASE_METHOD(NEBLJFixture, "NEB Onsager-Machlup spring",
                 "[neb][spring_om]") {
  ParametersLoadAccess::neb_options(params).spring.om.enabled = true;
  ParametersLoadAccess::neb_options(params).spring.om.k_scale = 1.0;
  ParametersLoadAccess::neb_options(params).spring.om.k_min = 0.1;
  ParametersLoadAccess::neb_options(params).spring.om.k_max = 20.0;
  ParametersLoadAccess::neb_options(params).spring.constant = 5.0;
  auto neb = makeNEB();
  neb->updateForces();

  for (long i = 1; i <= neb->numImages; i++) {
    REQUIRE(neb->projectedForce[i]->allFinite());
  }
}

} /* namespace tests */
