#!/usr/bin/env python
import sys

import pathfix
import io, atoms

p1 = io.loadcon(sys.argv[1])
p2 = io.loadcon(sys.argv[2])
if atoms.get_mappings(p1,p2):
    print "Found mappings."
    sys.exit(0)
else:
    print "Did not find mappings."
    sys.exit(1)

