#!/usr/bin/env python

import sys

import pathfix
import atoms
import numpy
import io

def abort():
    print "\n   usage: refinemv [input movie file] <intermediate frames>"
    sys.exit()

p = io.loadposcars(sys.argv[1])
if len(p) == 0:
    p = io.loadcons(sys.argv[1])
if len(p) == 0:
    abort()

        
try:
    N = int(sys.argv[2])
except:
    N = 1

f = open("foo.con", 'w')
f.close()

for i in range(len(p) - 1):
    v = atoms.pbc(p[i+1].r - p[i].r, p[i].box)
    d = numpy.linalg.norm(v)
    v /= d
    io.savecon("foo.con", p[i], 'a')
    for j in range(N):
        temp = p[i].copy()
        temp.r += j * (v * (d/(N+1)))
        io.savecon("foo.con", temp, 'a')
io.savecon("foo.con", p[len(p) - 1], 'a')

