
'''
Con(figuration) i/o library.

``.con`` frames are read and written with the **readcon** package
(:class:`readcon.ConFrame`). The in-memory working type is
:class:`eon.structure.Structure` (alias ``Atoms``).
'''
import configparser
import contextlib
#from io import BytesIO as StringIO
from io import StringIO
import logging
logger = logging.getLogger('io')
import numpy
import os

import pickle as pickle
import readcon
import stat
import tempfile

from eon.geometry.cell import box_to_length_angle, length_angle_to_box
from eon.structure import Structure

def save_prng_state():
    state = numpy.random.get_state()
    with open('prng.pkl', 'wb') as fh:
        pickle.dump(state, fh, pickle.HIGHEST_PROTOCOL)

def get_prng_state():
    with open('prng.pkl', 'rb') as fh:
        state = pickle.load(fh)
    numpy.random.set_state(state)

# Re-export cell helpers (used by callers / POSCAR path)
__all_cell__ = ("length_angle_to_box", "box_to_length_angle")


def _process_umask():
    mask = os.umask(0)
    os.umask(mask)
    return mask


# What open() and os.mkdir() give a new file or directory. mkstemp and
# mkdtemp ignore the umask and use 0600 / 0700, so anything staged through
# them is widened back to these before being moved into place.
_UMASK = _process_umask()
DEFAULT_FILE_MODE = 0o666 & ~_UMASK
DEFAULT_DIR_MODE = 0o777 & ~_UMASK


@contextlib.contextmanager
def atomic_write(path, mode='w'):
    '''
    Rewrite a file in one step, for callers that truncate and rewrite whole.
        path: destination file
        mode: 'w' or 'wb'
    The body writes to a temporary file in the destination's own directory,
    which is renamed over the destination on a clean exit. A reader sees
    either the old contents or the new ones, and a write that fails partway
    (a full disk, a killed process) leaves the destination as it was.
    mkstemp opens at 0600, so the destination's own mode carries over, or
    the umask default for a file that does not exist yet.
    '''
    directory = os.path.dirname(os.path.abspath(path))
    fd, temp_path = tempfile.mkstemp(dir=directory,
                                     prefix='.' + os.path.basename(path) + '.',
                                     suffix='.tmp')
    try:
        with os.fdopen(fd, mode) as f:
            yield f
        try:
            os.chmod(temp_path, stat.S_IMODE(os.stat(path).st_mode))
        except OSError:
            os.chmod(temp_path, DEFAULT_FILE_MODE)
        os.replace(temp_path, path)
    except BaseException:
        try:
            os.unlink(temp_path)
        except OSError:
            pass
        raise


def _maybe_open(target, mode, attr):
    '''
    Context manager over a filename or an already open file-like object.
        target: filename or file-like object
        mode:   mode passed to open() when target is a filename
        attr:   attribute marking target as file-like ('readline' or 'write')
    A handle opened here is closed on exit; one passed in by the caller is
    left open.
    '''
    if hasattr(target, attr):
        return contextlib.nullcontext(target)
    return open(target, mode)


def _frame_to_atoms(frame):
    """Convert a readcon.ConFrame to a Structure (canonical bridge)."""
    return Structure.from_conframe(frame)


def loadcons(filename):
    frames = readcon.read_con(filename)
    return [_frame_to_atoms(f) for f in frames]


def loadposcars(filename):
    p = []
    with open(filename, 'r') as filein:
        while True:
            try:
                p.append(loadposcar(filein))
            except (ValueError, IndexError):
                # End of file: the next header line is empty.
                return p


def loadcon(filein, reset = True):
    '''
    Load a con file via readcon; return a Structure.
        filein: may be either a filename or a file-like object
    '''
    if hasattr(filein, 'readline'):
        content = filein.read()
        if reset:
            filein.seek(0)
        frames = readcon.read_con_string(content)
        if not frames:
            raise IOError("No frames found in con data")
        return _frame_to_atoms(frames[0])
    return _frame_to_atoms(readcon.read_first_frame(filein))

def _atoms_to_frame(p):
    """Convert a Structure (or Structure-like) to a readcon.ConFrame."""
    if isinstance(p, Structure):
        return p.to_conframe()
    lengths, angles = box_to_length_angle(p.box)
    atom_list = []
    for i in range(len(p)):
        atom_list.append(
            readcon.Atom(
                symbol=p.names[i],
                x=float(p.r[i][0]),
                y=float(p.r[i][1]),
                z=float(p.r[i][2]),
                fixed=[p.free[i] == 0] * 3,
                atom_id=i + 1,
                mass=float(p.mass[i]),
            )
        )
    return readcon.ConFrame(
        cell=list(lengths),
        angles=list(angles),
        atoms=atom_list,
        prebox_header=["Generated by eOn", ""],
    )


def savecon(fileout, p, w = 'w'):
    '''
    Save a con file via readcon.
        fileout: can be either a file name or a file-like object
        p:       Structure (or Structure-like) to save
        w:       write/append flag
    '''
    frame = _atoms_to_frame(p)
    if hasattr(fileout, 'write'):
        text = readcon.write_con_string([frame])
        fileout.write(text)
    else:
        if w == 'a' and os.path.exists(fileout):
            existing = readcon.read_con(fileout)
            existing.append(frame)
            readcon.write_con(fileout, existing)
        else:
            readcon.write_con(fileout, [frame])


def load_mode(modefilein):
    '''
    Reads a mode.dat file into an N by 3 numpy array
        modefilein: may be either a file-like object of a filename
    '''
    with _maybe_open(modefilein, 'r', 'readline') as f:
        if len(f.readline().split()) == 3:
            f.seek(0)
        lines = f.readlines()
    mode = []
    for line in lines:
        l = line.split()
        if not l:
            continue
        if len(l) < 3:
            raise IOError("Malformed mode.dat line, expected three columns: %r" % line)
        for j in range(3):
            mode.append(float(l[j]))
    return numpy.array(mode).reshape(len(mode)//3, 3)

def save_mode(modefileout, displace_vector):
    '''
    Saves an Nx3 numpy array into a mode.dat file.
        modefileout:     may be either a filename or file-like object
        displace_vector: the mode (Nx3 numpy array)
    '''
    with _maybe_open(modefileout, 'w', 'write') as f:
        for i in range(len(displace_vector)):
            f.write("%.3f %.3f %.3f\n" % (displace_vector[i][0],
                displace_vector[i][1], displace_vector[i][2]))


def save_results_dat(fileout, results):
    '''
    Saves a results.dat file from a dictionary
        fileout: may be either a filename or a file-like object
        results: dictionary of values, written one "<value> <key>" line each
    '''
    with _maybe_open(fileout, 'w', 'write') as f:
        for key in results:
            f.write("%s %s\n" % (results[key], key))

def modify_config(config_path, changes):
    parser = configparser.ConfigParser()
    parser.read(config_path)
    for change in changes:
        parser.set(*change)
    config_str_io = StringIO()
    parser.write(config_str_io)
    config_str_io.seek(0)
    return config_str_io

def parse_results(filein):
    '''
    Reads a results.dat file and gives a dictionary of the values contained therein
    '''
    results = {}
    with _maybe_open(filein, 'r', 'readline') as f:
        f.seek(0)
        for line in f:
            line = line.split()
            if len(line) < 2:
                continue
            if '.' in line[0]:
                try:
                    results[line[1]] = float(line[0])
                except ValueError:
                    results[line[1]] = line[0]
            else:
                try:
                    results[line[1]] = int(line[0])
                except ValueError:
                    results[line[1]] = line[0]

    return results

def loadposcar(filein):
    '''
    Load the POSCAR file named filename and returns an atoms object
    '''
    if hasattr(filein, 'readline'):
        f = filein
    else:
        f = open(filein, 'r')
    # Line 1: Atom types
    AtomTypes = f.readline().split()
    # Line 2: scaling of coordinates
    scale = float(f.readline())
    # Lines 3-5: the box
    box = numpy.zeros((3, 3))
    for i in range(3):
        line = f.readline().split()
        box[i] = numpy.array([float(line[0]), float(line[1]), float(line[2])]) * scale
    # Line 6: number of atoms of each type.
    line = f.readline().split()
    NumAtomsPerType = []
    for l in line:
        NumAtomsPerType.append(int(l))
    # Now have enough info to make the Structure object.
    num_atoms = sum(NumAtomsPerType)
    p = Structure(num_atoms)
    # Fill in the box.
    p.box = box
    # Line 7: selective or cartesian
    sel = f.readline()[0]
    selective_flag = (sel == 's' or sel == 'S')
    if not selective_flag:
        car = sel
    else:
        car = f.readline()[0]
    direct_flag = not (car == 'c' or car == 'C' or car == 'k' or car == 'K')
    atom_index = 0
    for i in range(len(NumAtomsPerType)):
        for j in range(NumAtomsPerType[i]):
            p.names[atom_index] = AtomTypes[i]
            line = f.readline().split()
            if(selective_flag):
                assert len(line) >= 6
            else:
                assert len(line) >= 3
            pos = line[0:3]
            if selective_flag:
                sel = line[3:7]
                if sel[0] == 'T' or sel[0] == 't':
                    p.free[atom_index] = 1
                elif sel[0] == 'F' or sel[0] == 'f':
                    p.free[atom_index] = 0
            p.r[atom_index] = numpy.array([float(q) for q in pos])
            if direct_flag:
                p.r[atom_index] = numpy.dot(p.r[atom_index], p.box)
            else:
                p.r[atom_index] *= scale
            atom_index += 1
    return p


def saveposcar(fileout, p, w='w', direct = False):
    '''
    Save a POSCAR
        fileout: name to save it under
        point:    atoms object to save
        w:        write/append flag
    '''
    if hasattr(fileout, 'write'):
        poscar = fileout
    else:
        poscar = open(fileout, w)
    atom_types = []
    num_each_type = {}
    for name in p.names:
        if not name in atom_types:
            atom_types.append(name)
            num_each_type[name] = 1
        else:
            num_each_type[name] += 1
    poscar.write(" ".join(atom_types)+'\n') #Line 1: Atom type
    poscar.write("1.0\n") #Line 2: scaling
    for i in range(3):
        poscar.write(" ".join(['%20.14f' % s for s in p.box[i]])+'\n')  #lines 3-5: box
    poscar.write(" ".join(atom_types)+'\n') #Line 6: Atom type
    poscar.write(" ".join(['%s' % num_each_type[key] for key in atom_types])+'\n')
    poscar.write('Selective Dynamics\n') #line 7: selective dynamics
    if direct:
        poscar.write('Direct\n')  #line 8 cartesian coordinates
        ibox = numpy.linalg.inv(numpy.array(p.box))
        positions = numpy.dot(p.r, ibox)
    else:
        poscar.write('Cartesian\n') #line 8 cartesian coordinates
        positions = p.r
    for i in range(len(p)):
            posline = " ".join(['%20.14f' % s for s in positions[i]]) + " "
            for j in range(3):
                if(p.free[i]):
                    posline+='   T'
                else:
                    posline+='   F'
            poscar.write(posline+'\n')


from configparser import ConfigParser as SCP
class ini(SCP):

    def __init__(self, filenames):
        self.loaded = False
        self.filenames = filenames
        SCP.__init__(self)

    def read(self):
        self.loaded = True
        SCP.read(self, self.filenames)

    def get(self, section, option, default="ini_no_default", **kwargs):
#    def get(self, section, option, default="ini_no_default"):
        if not self.loaded:
            self.read()
        try:
            SCP.read(self, self.filenames)
            #value = SCP.get(self, section, option, raw=True, **kwargs)
            value = SCP.get(self, section, option, **kwargs)
            #value = SCP.get(self, section, option, raw=True)
            #value = SCP.get(self, section, option)
        except:
            if default == "ini_no_default":
                raise NameError("Section or option missing, no default specified")
            return default
        try:
            return int(value)
        except ValueError:
            pass
        try:
            return float(value)
        except ValueError:
            pass
        if value.lower() == 'true':
            return True
        if value.lower() == 'false':
            return False
        return value

    def getint(self, *args):
        raise NotImplementedError("Use the get function with this ConfigParser wrapper")
    def getfloat(self, *args):
        raise NotImplementedError("Use the get function with this ConfigParser wrapper")
    def getboolean(self, *args):
        raise NotImplementedError("Use the get function with this ConfigParser wrapper")

    def set(self, section, option, value):
        if section not in self.sections():
            self.add_section(section)
        SCP.set(self, section, option, str(value))
        if type(self.filenames) == str:
            name = self.filenames
        else:
            name = self.filenames[-1]
        with atomic_write(name) as configfile:
            self.write(configfile)


class Dynamics:
    """ The Dynamics class handles I/O for the dynamics.txt file of an aKMC simulation. """

    def __init__(self, filename):
        self.filename = filename
        if not os.path.exists(filename):
            f = open(self.filename, 'w')
            header = "%12s  %12s  %12s  %12s  %12s  %12s  %12s  %12s  %12s\n" % ('step-number', 'reactant-id', 'process-id', 'product-id', 'step-time', 'total-time', 'barrier', 'rate', 'energy')
            f.write(header)
            f.write("-" * len(header))
            f.write("\n")
            f.close()
            self.next_step = 0

        # read last lines of the file to determine iteration nr
        else:
            f = open(self.filename,'r')
            f.seek(0,2)	#seek to EOF
            fsize = f.tell()
            # seek 1024 bytes back (or to beginning of file if fsize < 1024 )
            # last line must be contained in this block
            f.seek( max( fsize - 1024 , 0 ) , 0)
            lines = f.readlines()
            self.next_step = int ( lines[-1].split()[0] ) + 1 # determine iteration nr of next step

    def append(self, reactant_id, process_id, product_id, step_time, total_time, barrier, rate, energy):
        f = open(self.filename, 'a')
        f.write("%12d  %12d  %12d  %12d  %12e  %12e  %12f  %12e  %12f\n" % (self.next_step, reactant_id, process_id, product_id, step_time, total_time, barrier, rate, energy))
        f.close()
        self.next_step += 1

    def append_sb(self, reactant_id, process_id, product_id, step_time, total_time, basin_id, rate, energy):
        f = open(self.filename, 'a')
        f.write("%12d  %12d  %12d  %12d  %12e  %12e  %12d  %12e  %12f\n" % (self.next_step, reactant_id, process_id, product_id, step_time, total_time, basin_id, rate, energy))
        f.close()
        self.next_step += 1

    def get(self):
        f = open(self.filename, 'r')
        lines = f.readlines()[2:]
        f.close()
        data = []
        for line in lines:
            split = line.split()
            data.append({"reactant":    int(split[1]),
                         "process":     int(split[2]),
                         "product":     int(split[3]),
                         "steptime":    float(split[4]),
                         "totaltime":   float(split[5]),
                         "barrier":     float(split[6]),
                         "prefactor":   float(split[7])})
        return data

def load_potfiles(pot_dir):
    ret = {}
    if os.path.isdir(pot_dir):
        for name in os.listdir(pot_dir):
            if os.path.isdir(name):
                continue
            a = open(os.path.join(pot_dir, name), 'r')
            b = StringIO("".join(a.readlines()))
            c = os.stat(os.path.join(pot_dir, name)).st_mode
            ret[name] = (b,c)
    return ret

class TableException(Exception):
    pass

class Table:
    """
    A class that provides a nice io abstraction for table like data.  The data
    is saved in a pretty printed format. Also provides nice data retrival
    methods.

    >>> t = Table("sample.tbl", ['id', 'name', 'age' ])
    >>> t.eagerwrite = False
    >>> t.add_row({'id':0,'name':"Sam","age":24})
    >>> t.add_row({'id':1,'name':"David","age":50})
    >>> t.add_row({'id':2,'name':"Anna","age":21})
    >>> t #doctest: +NORMALIZE_WHITESPACE
        id name  age
        -- ----- ---
        0  Sam   24
        1  David 50
        2  Anna  21

    Rows can be accessed directly:
    >>> t.rows[1] #doctest: +SKIP
        {'age': 50, 'id': 1, 'name': 'David'}
    >>> t.max_value('age') #doctest: +NORMALIZE_WHITESPACE
        50
    >>> t.min_row('age') #doctest: +NORMALIZE_WHITESPACE +SKIP
        {'age': 21, 'id': 2, 'name': 'Anna'}
    >>> sorted(t.min_row('id').items()) #doctest: +NORMALIZE_WHITESPACE
        [('age', 24), ('id', 0), ('name', 'Sam')]
    >>> len(t) #doctest: +NORMALIZE_WHITESPACE
        3
    >>> sum(t.getcolumn('age')) #doctest: +NORMALIZE_WHITESPACE
        95
    >>> t.write() #doctest: +SKIP

    The table can be loaded from disk without specifying columns. This is
    slightly unsafe because the columns can't be checked, but it could cut down
    on the verbosity in some places.
    >>> t2 = Table("sample.tbl") #doctest: +SKIP
"""

    #XXX: This is the number of digits that a floating point number gets
    #     serialized with. Should it be some sort of config option?
    #     Or is there just a good default?

    def __init__(self, filename, columns=None, overwrite=False):
        self.filename = filename
        self.columns = columns
        self.rows = []
        self.columntypes = {}
        self.columnwidths = {}
        self.initialized = False
        self.overwrite = overwrite

        self.floatprecision = 6
        self.eagerwrite = True

    def init(self):
        """Checks to see if self.filename exists. If it does self.rows
           will be initialized from disk."""
        self.initialized = True
        if os.path.isfile(self.filename) and not self.overwrite:
            self.read(self.filename)
        else:
            if self.columns is None:
                raise TableException("Columns are not optional for new tables")

            for c in self.columns:
                self.columnwidths[c] = len(c)

    def read(self, filename):
        self.eagerwrite = False
        f = open(self.filename, "r")
        filecolumns = f.readline().split()
        if self.columns != None:
            if filecolumns != self.columns:
                raise TableException("Column name mismatch: %s" % filename)
        else:
            self.columns = filecolumns

        for c in self.columns:
            self.columnwidths[c] = len(c)

        # skip comment line
        f.readline()

        for line in f:
            fields = line.split()
            row = {}
            coli = 0
            for field in fields:
                try:
                    field = int(field)
                except ValueError:
                    try:
                        field = float(field)
                    except ValueError:
                        field = field.strip()
                        pass
                row[self.columns[coli]] = field
                coli += 1
            self.add_row(row)
        f.close()
        self.eagerwrite = True

    def __repr__(self):
        if not self.initialized:
            self.init()
        f = StringIO()
        self.writefilehandle(f)
        return f.getvalue()

    def __len__(self):
        if not self.initialized:
            self.init()
        return len(self.rows)

    def __iter__(self):
        for row in self.rows:
            yield row

    def write(self):
        if not self.initialized:
            self.init()
        #print("into table write: ",self.filename)
        with atomic_write(self.filename) as f:
            self.writefilehandle(f)

    def writefilehandle(self, filehandle):
        f = filehandle
        line = ' '.join([ "%-*s"%(self.columnwidths[c], c) for c in self.columns ])
        f.write(line+"\n")

        line = ''
        for c in self.columns:
            line += '-'*self.columnwidths[c]+' '
        f.write(line+'\n')

        for row in self.rows:
            line = ""
            for c in self.columns:
                if self.columntypes[c] == float:
                    line += "%#-*.*G " % (self.columnwidths[c],self.floatprecision,
                                         row[c])
                else:
                    line += "%-*s " % (self.columnwidths[c],row[c])
            f.write(line+"\n")

    def add_row(self, row):
        if not self.initialized:
            self.init()
        mismatched_columns = set(self.columns).symmetric_difference(set(row.keys()))
        if len(mismatched_columns) != 0:
            raise TableException("Mismatched columns %s" % str(mismatched_columns))

        if len(self.rows) == 0:
            for c in row:
                self.columntypes[c] = type(row[c])
        else:
            for c in row:
                if type(row[c]) != self.columntypes[c]:
                    raise TableException("Type mismatch for column %s" % c)

        for c in row:
            if self.columntypes[c] == float:
                self.columnwidths[c] = max(self.columnwidths[c], self.floatprecision+5)
            else:
                self.columnwidths[c] = max(self.columnwidths[c], len(str(row[c])))

        self.rows.append(row)
        if self.eagerwrite:
            self.write()

    def delete_row(self, column, value):
        if not self.initialized:
            self.init()
        rows_to_delete = []
        for row in self.rows:
            if row[column] == value:
                rows_to_delete.append(row)
#        map(self.rows.remove, rows_to_delete)
        for row in rows_to_delete:
            self.rows.remove(row)
        if self.eagerwrite:
            self.write()
        return len(rows_to_delete)

    def delete_row_func(self, column, func):
        if not self.initialized:
            self.init()

        rows_to_delete = []
        for row in self.rows:
            if func(row[column]):
                rows_to_delete.append(row)
#        map(self.rows.remove, rows_to_delete)
        for row in rows_to_delete:
            self.rows.remove(row)
        if self.eagerwrite:
            self.write()
        return len(rows_to_delete)

    def find_value(self, column, func):
        if not self.initialized:
            self.init()
        value = None
        for row in self.rows:
            if value is None:
                value = row[column]
                continue
            value = func(value, row[column])
        return value

    def find_row(self, column, func):
        if not self.initialized:
            self.init()
        value = None
        for row in self.rows:
            if value is None:
                value = row
                continue

            if func(row[column],value[column])==row[column]:
                value = row
        return value

    def min_value(self, column):
        return self.find_value(column, min)
    def min_row(self, column):
        return self.find_row(column, min)
    def max_value(self, column):
        return self.find_value(column, max)
    def max_row(self, column):
        return self.find_row(column, max)

    def get_row(self, column, value):
        if not self.initialized:
            self.init()

        for row in self.rows:
            if row[column] == value:
                return row

        return None

    def get_rows(self, column, value):
        if not self.initialized:
            self.init()

        result = []
        for row in self.rows:
            if row[column] == value:
                result.append(row)

        return result

    def get_column(self, column):
        if not self.initialized:
            self.init()
        results = []
        for row in self.rows:
            results.append(row[column])
        return results

if __name__=='__main__':
    import doctest
    doctest.testmod()
