var annotated_dup =
[
    [ "eonc", "namespaceeonc.html", [
      [ "geometry", "namespaceeonc_1_1geometry.html", [
        [ "atom", "structeonc_1_1geometry_1_1atom.html", "structeonc_1_1geometry_1_1atom" ],
        [ "by_atom", "structeonc_1_1geometry_1_1by__atom.html", "structeonc_1_1geometry_1_1by__atom" ]
      ] ],
      [ "io", "namespaceeonc_1_1io.html", [
        [ "ConFrameMetadata", "structeonc_1_1io_1_1ConFrameMetadata.html", "structeonc_1_1io_1_1ConFrameMetadata" ],
        [ "ConMetadataText", "structeonc_1_1io_1_1ConMetadataText.html", "structeonc_1_1io_1_1ConMetadataText" ],
        [ "ConMetadataValue", "structeonc_1_1io_1_1ConMetadataValue.html", "structeonc_1_1io_1_1ConMetadataValue" ]
      ] ],
      [ "log", "namespaceeonc_1_1log.html", [
        [ "Scoped", "structeonc_1_1log_1_1Scoped.html", "structeonc_1_1log_1_1Scoped" ],
        [ "FileScoped", "structeonc_1_1log_1_1FileScoped.html", "structeonc_1_1log_1_1FileScoped" ]
      ] ],
      [ "neb", "namespaceeonc_1_1neb.html", [
        [ "zoom", "namespaceeonc_1_1neb_1_1zoom.html", [
          [ "Window", "structeonc_1_1neb_1_1zoom_1_1Window.html", "structeonc_1_1neb_1_1zoom_1_1Window" ]
        ] ],
        [ "CartesianStep", "structeonc_1_1neb_1_1CartesianStep.html", "structeonc_1_1neb_1_1CartesianStep" ],
        [ "DNEB_Projection", "structeonc_1_1neb_1_1DNEB__Projection.html", "structeonc_1_1neb_1_1DNEB__Projection" ],
        [ "ExtremaResult", "structeonc_1_1neb_1_1ExtremaResult.html", "structeonc_1_1neb_1_1ExtremaResult" ],
        [ "ImageForceData", "structeonc_1_1neb_1_1ImageForceData.html", "structeonc_1_1neb_1_1ImageForceData" ],
        [ "ImprovedTangent", "structeonc_1_1neb_1_1ImprovedTangent.html", "structeonc_1_1neb_1_1ImprovedTangent" ],
        [ "JointBlock", "structeonc_1_1neb_1_1JointBlock.html", "structeonc_1_1neb_1_1JointBlock" ],
        [ "NEB_Projection", "structeonc_1_1neb_1_1NEB__Projection.html", "structeonc_1_1neb_1_1NEB__Projection" ],
        [ "OCINEBController", "classeonc_1_1neb_1_1OCINEBController.html", "classeonc_1_1neb_1_1OCINEBController" ],
        [ "OnsagerMachlupSpring", "structeonc_1_1neb_1_1OnsagerMachlupSpring.html", "structeonc_1_1neb_1_1OnsagerMachlupSpring" ],
        [ "PlainEB", "structeonc_1_1neb_1_1PlainEB.html", "structeonc_1_1neb_1_1PlainEB" ],
        [ "SimpleTangent", "structeonc_1_1neb_1_1SimpleTangent.html", "structeonc_1_1neb_1_1SimpleTangent" ],
        [ "SpringResult", "structeonc_1_1neb_1_1SpringResult.html", "structeonc_1_1neb_1_1SpringResult" ],
        [ "UniformSpring", "structeonc_1_1neb_1_1UniformSpring.html", "structeonc_1_1neb_1_1UniformSpring" ],
        [ "WeightedSpring", "structeonc_1_1neb_1_1WeightedSpring.html", "structeonc_1_1neb_1_1WeightedSpring" ]
      ] ],
      [ "params_ssot", "namespaceeonc_1_1params__ssot.html", [
        [ "GeneratedDefaults", "structeonc_1_1params__ssot_1_1GeneratedDefaults.html", "structeonc_1_1params__ssot_1_1GeneratedDefaults" ]
      ] ],
      [ "pathintegral", "namespaceeonc_1_1pathintegral.html", [
        [ "Options", "structeonc_1_1pathintegral_1_1Options.html", "structeonc_1_1pathintegral_1_1Options" ],
        [ "RingPolymer", "classeonc_1_1pathintegral_1_1RingPolymer.html", "classeonc_1_1pathintegral_1_1RingPolymer" ],
        [ "Sample", "structeonc_1_1pathintegral_1_1Sample.html", "structeonc_1_1pathintegral_1_1Sample" ]
      ] ],
      [ "piqtst", "namespaceeonc_1_1piqtst.html", [
        [ "Coordinate", "structeonc_1_1piqtst_1_1Coordinate.html", "structeonc_1_1piqtst_1_1Coordinate" ],
        [ "Plane", "structeonc_1_1piqtst_1_1Plane.html", "structeonc_1_1piqtst_1_1Plane" ],
        [ "Rate", "structeonc_1_1piqtst_1_1Rate.html", "structeonc_1_1piqtst_1_1Rate" ],
        [ "Recrossing", "structeonc_1_1piqtst_1_1Recrossing.html", "structeonc_1_1piqtst_1_1Recrossing" ],
        [ "RecrossingOptions", "structeonc_1_1piqtst_1_1RecrossingOptions.html", "structeonc_1_1piqtst_1_1RecrossingOptions" ],
        [ "ScanOptions", "structeonc_1_1piqtst_1_1ScanOptions.html", "structeonc_1_1piqtst_1_1ScanOptions" ]
      ] ],
      [ "tunneling", "namespaceeonc_1_1tunneling.html", [
        [ "Instanton", "structeonc_1_1tunneling_1_1Instanton.html", "structeonc_1_1tunneling_1_1Instanton" ],
        [ "InstantonOptions", "structeonc_1_1tunneling_1_1InstantonOptions.html", "structeonc_1_1tunneling_1_1InstantonOptions" ],
        [ "Profile", "classeonc_1_1tunneling_1_1Profile.html", "classeonc_1_1tunneling_1_1Profile" ],
        [ "RateInstanton", "structeonc_1_1tunneling_1_1RateInstanton.html", "structeonc_1_1tunneling_1_1RateInstanton" ],
        [ "RateInstantonOptions", "structeonc_1_1tunneling_1_1RateInstantonOptions.html", "structeonc_1_1tunneling_1_1RateInstantonOptions" ],
        [ "RingSpectrum", "structeonc_1_1tunneling_1_1RingSpectrum.html", "structeonc_1_1tunneling_1_1RingSpectrum" ],
        [ "Splitting", "structeonc_1_1tunneling_1_1Splitting.html", "structeonc_1_1tunneling_1_1Splitting" ]
      ] ],
      [ "xtsci_eindir", "namespaceeonc_1_1xtsci__eindir.html", [
        [ "View", "structeonc_1_1xtsci__eindir_1_1View.html", "structeonc_1_1xtsci__eindir_1_1View" ]
      ] ],
      [ "ams_options_t", "structeonc_1_1ams__options__t.html", "structeonc_1_1ams__options__t" ],
      [ "artn_options_t", "structeonc_1_1artn__options__t.html", "structeonc_1_1artn__options__t" ],
      [ "ARTnResource", "classeonc_1_1ARTnResource.html", "classeonc_1_1ARTnResource" ],
      [ "ARTnSaddleSearch", "classeonc_1_1ARTnSaddleSearch.html", "classeonc_1_1ARTnSaddleSearch" ],
      [ "ase_nwchem_options_t", "structeonc_1_1ase__nwchem__options__t.html", "structeonc_1_1ase__nwchem__options__t" ],
      [ "ase_orca_options_t", "structeonc_1_1ase__orca__options__t.html", "structeonc_1_1ase__orca__options__t" ],
      [ "AtomicGPDimer", "classeonc_1_1AtomicGPDimer.html", "classeonc_1_1AtomicGPDimer" ],
      [ "basin_hopping_options_t", "structeonc_1_1basin__hopping__options__t.html", "structeonc_1_1basin__hopping__options__t" ],
      [ "BasinHoppingJob", "classeonc_1_1BasinHoppingJob.html", "classeonc_1_1BasinHoppingJob" ],
      [ "BasinHoppingSaddleSearch", "classeonc_1_1BasinHoppingSaddleSearch.html", "classeonc_1_1BasinHoppingSaddleSearch" ],
      [ "bgsd_options_t", "structeonc_1_1bgsd__options__t.html", "structeonc_1_1bgsd__options__t" ],
      [ "BGSDObjectiveFunction", "classeonc_1_1BGSDObjectiveFunction.html", "classeonc_1_1BGSDObjectiveFunction" ],
      [ "BiasedGradientSquaredDescent", "classeonc_1_1BiasedGradientSquaredDescent.html", "classeonc_1_1BiasedGradientSquaredDescent" ],
      [ "BondBoost", "classeonc_1_1BondBoost.html", "classeonc_1_1BondBoost" ],
      [ "catlearn_options_t", "structeonc_1_1catlearn__options__t.html", "structeonc_1_1catlearn__options__t" ],
      [ "CollectiveIDPPObjectiveFunction", "classeonc_1_1CollectiveIDPPObjectiveFunction.html", "classeonc_1_1CollectiveIDPPObjectiveFunction" ],
      [ "ConjugateGradients", "classeonc_1_1ConjugateGradients.html", "classeonc_1_1ConjugateGradients" ],
      [ "constants_t", "structeonc_1_1constants__t.html", "structeonc_1_1constants__t" ],
      [ "Davidson", "classeonc_1_1Davidson.html", "classeonc_1_1Davidson" ],
      [ "davidson_options_t", "structeonc_1_1davidson__options__t.html", "structeonc_1_1davidson__options__t" ],
      [ "debug_options_t", "structeonc_1_1debug__options__t.html", "structeonc_1_1debug__options__t" ],
      [ "DecodedDiv", "structeonc_1_1DecodedDiv.html", "structeonc_1_1DecodedDiv" ],
      [ "dftd_options_t", "structeonc_1_1dftd__options__t.html", "structeonc_1_1dftd__options__t" ],
      [ "Dimer", "classeonc_1_1Dimer.html", "classeonc_1_1Dimer" ],
      [ "dimer_options_t", "structeonc_1_1dimer__options__t.html", "structeonc_1_1dimer__options__t" ],
      [ "DimerModeLostException", "classeonc_1_1DimerModeLostException.html", "classeonc_1_1DimerModeLostException" ],
      [ "DimerModeRestoredException", "classeonc_1_1DimerModeRestoredException.html", "classeonc_1_1DimerModeRestoredException" ],
      [ "DimerRotationResult", "structeonc_1_1DimerRotationResult.html", "structeonc_1_1DimerRotationResult" ],
      [ "Dynamics", "classeonc_1_1Dynamics.html", "classeonc_1_1Dynamics" ],
      [ "dynamics_options_t", "structeonc_1_1dynamics__options__t.html", "structeonc_1_1dynamics__options__t" ],
      [ "DynamicsConfig", "structeonc_1_1DynamicsConfig.html", "structeonc_1_1DynamicsConfig" ],
      [ "DynamicsJob", "classeonc_1_1DynamicsJob.html", "classeonc_1_1DynamicsJob" ],
      [ "DynamicsSaddleSearch", "classeonc_1_1DynamicsSaddleSearch.html", "classeonc_1_1DynamicsSaddleSearch" ],
      [ "expr_options_t", "structeonc_1_1expr__options__t.html", "structeonc_1_1expr__options__t" ],
      [ "FiniteDifferenceJob", "classeonc_1_1FiniteDifferenceJob.html", "classeonc_1_1FiniteDifferenceJob" ],
      [ "FIRE", "classeonc_1_1FIRE.html", "classeonc_1_1FIRE" ],
      [ "ForceCallTimer", "classeonc_1_1ForceCallTimer.html", "classeonc_1_1ForceCallTimer" ],
      [ "FPEGuard", "classeonc_1_1FPEGuard.html", "classeonc_1_1FPEGuard" ],
      [ "FPEHandler", "classeonc_1_1FPEHandler.html", "classeonc_1_1FPEHandler" ],
      [ "GleThermostat", "classeonc_1_1GleThermostat.html", "classeonc_1_1GleThermostat" ],
      [ "global_optimization_options_t", "structeonc_1_1global__optimization__options__t.html", "structeonc_1_1global__optimization__options__t" ],
      [ "GlobalOptimization", "classeonc_1_1GlobalOptimization.html", "classeonc_1_1GlobalOptimization" ],
      [ "GlobalOptimizationJob", "classeonc_1_1GlobalOptimizationJob.html", "classeonc_1_1GlobalOptimizationJob" ],
      [ "gp_surrogate_options_t", "structeonc_1_1gp__surrogate__options__t.html", "structeonc_1_1gp__surrogate__options__t" ],
      [ "gpr_dimer_options_t", "structeonc_1_1gpr__dimer__options__t.html", "structeonc_1_1gpr__dimer__options__t" ],
      [ "GPSurrogateJob", "classeonc_1_1GPSurrogateJob.html", "classeonc_1_1GPSurrogateJob" ],
      [ "Hessian", "classeonc_1_1Hessian.html", "classeonc_1_1Hessian" ],
      [ "hessian_options_t", "structeonc_1_1hessian__options__t.html", "structeonc_1_1hessian__options__t" ],
      [ "HessianJob", "classeonc_1_1HessianJob.html", "classeonc_1_1HessianJob" ],
      [ "Hyperdynamics", "classeonc_1_1Hyperdynamics.html", "classeonc_1_1Hyperdynamics" ],
      [ "hyperdynamics_options_t", "structeonc_1_1hyperdynamics__options__t.html", "structeonc_1_1hyperdynamics__options__t" ],
      [ "IARTnResource", "classeonc_1_1IARTnResource.html", "classeonc_1_1IARTnResource" ],
      [ "IDPPObjectiveFunction", "classeonc_1_1IDPPObjectiveFunction.html", "classeonc_1_1IDPPObjectiveFunction" ],
      [ "IIRAResource", "classeonc_1_1IIRAResource.html", "classeonc_1_1IIRAResource" ],
      [ "ILammpsLoader", "classeonc_1_1ILammpsLoader.html", "classeonc_1_1ILammpsLoader" ],
      [ "IMetatomicLoader", "classeonc_1_1IMetatomicLoader.html", "classeonc_1_1IMetatomicLoader" ],
      [ "ImprovedDimer", "classeonc_1_1ImprovedDimer.html", "classeonc_1_1ImprovedDimer" ],
      [ "instanton_options_t", "structeonc_1_1instanton__options__t.html", "structeonc_1_1instanton__options__t" ],
      [ "InstantonJob", "classeonc_1_1InstantonJob.html", "classeonc_1_1InstantonJob" ],
      [ "IPluginLoader", "classeonc_1_1IPluginLoader.html", "classeonc_1_1IPluginLoader" ],
      [ "IPotRegistry", "classeonc_1_1IPotRegistry.html", "classeonc_1_1IPotRegistry" ],
      [ "ira_options_t", "structeonc_1_1ira__options__t.html", "structeonc_1_1ira__options__t" ],
      [ "IRACompare", "classeonc_1_1IRACompare.html", "classeonc_1_1IRACompare" ],
      [ "IRAResource", "classeonc_1_1IRAResource.html", "classeonc_1_1IRAResource" ],
      [ "Job", "classeonc_1_1Job.html", "classeonc_1_1Job" ],
      [ "JobResultEnvelope", "structeonc_1_1JobResultEnvelope.html", "structeonc_1_1JobResultEnvelope" ],
      [ "LammpsLoader", "classeonc_1_1LammpsLoader.html", "classeonc_1_1LammpsLoader" ],
      [ "Lanczos", "classeonc_1_1Lanczos.html", "classeonc_1_1Lanczos" ],
      [ "lanczos_options_t", "structeonc_1_1lanczos__options__t.html", "structeonc_1_1lanczos__options__t" ],
      [ "LBFGS", "classeonc_1_1LBFGS.html", "classeonc_1_1LBFGS" ],
      [ "LORRotation", "classeonc_1_1LORRotation.html", "classeonc_1_1LORRotation" ],
      [ "LowestEigenmode", "classeonc_1_1LowestEigenmode.html", "classeonc_1_1LowestEigenmode" ],
      [ "main_options_t", "structeonc_1_1main__options__t.html", "structeonc_1_1main__options__t" ],
      [ "Matter", "classeonc_1_1Matter.html", "classeonc_1_1Matter" ],
      [ "metatomic_options_t", "structeonc_1_1metatomic__options__t.html", "structeonc_1_1metatomic__options__t" ],
      [ "MetatomicDynPot", "classeonc_1_1MetatomicDynPot.html", "classeonc_1_1MetatomicDynPot" ],
      [ "MetatomicLoader", "classeonc_1_1MetatomicLoader.html", "classeonc_1_1MetatomicLoader" ],
      [ "MinimizationJob", "classeonc_1_1MinimizationJob.html", "classeonc_1_1MinimizationJob" ],
      [ "MinModeObjectiveFunction", "classeonc_1_1MinModeObjectiveFunction.html", "classeonc_1_1MinModeObjectiveFunction" ],
      [ "MinModeSaddleSearch", "classeonc_1_1MinModeSaddleSearch.html", "classeonc_1_1MinModeSaddleSearch" ],
      [ "monte_carlo_options_t", "structeonc_1_1monte__carlo__options__t.html", "structeonc_1_1monte__carlo__options__t" ],
      [ "MonteCarlo", "classeonc_1_1MonteCarlo.html", "classeonc_1_1MonteCarlo" ],
      [ "MonteCarloJob", "classeonc_1_1MonteCarloJob.html", "classeonc_1_1MonteCarloJob" ],
      [ "mopac_options_t", "structeonc_1_1mopac__options__t.html", "structeonc_1_1mopac__options__t" ],
      [ "neb_options_t", "structeonc_1_1neb__options__t.html", "structeonc_1_1neb__options__t" ],
      [ "NEBObjectiveFunction", "classeonc_1_1NEBObjectiveFunction.html", "classeonc_1_1NEBObjectiveFunction" ],
      [ "NudgedElasticBand", "classeonc_1_1NudgedElasticBand.html", "classeonc_1_1NudgedElasticBand" ],
      [ "NudgedElasticBandJob", "classeonc_1_1NudgedElasticBandJob.html", "classeonc_1_1NudgedElasticBandJob" ],
      [ "ObjectiveFunction", "classeonc_1_1ObjectiveFunction.html", "classeonc_1_1ObjectiveFunction" ],
      [ "oh_tst_options_t", "structeonc_1_1oh__tst__options__t.html", "structeonc_1_1oh__tst__options__t" ],
      [ "OHTSTJob", "classeonc_1_1OHTSTJob.html", "classeonc_1_1OHTSTJob" ],
      [ "Optimizer", "classeonc_1_1Optimizer.html", "classeonc_1_1Optimizer" ],
      [ "optimizer_options_t", "structeonc_1_1optimizer__options__t.html", "structeonc_1_1optimizer__options__t" ],
      [ "OptimizerConfig", "structeonc_1_1OptimizerConfig.html", "structeonc_1_1OptimizerConfig" ],
      [ "parallel_replica_options_t", "structeonc_1_1parallel__replica__options__t.html", "structeonc_1_1parallel__replica__options__t" ],
      [ "ParallelReplicaJob", "classeonc_1_1ParallelReplicaJob.html", "classeonc_1_1ParallelReplicaJob" ],
      [ "Parameters", "classeonc_1_1Parameters.html", "classeonc_1_1Parameters" ],
      [ "ParametersLoadAccess", "structeonc_1_1ParametersLoadAccess.html", "structeonc_1_1ParametersLoadAccess" ],
      [ "PluginLoader", "classeonc_1_1PluginLoader.html", "classeonc_1_1PluginLoader" ],
      [ "PointJob", "classeonc_1_1PointJob.html", "classeonc_1_1PointJob" ],
      [ "Potential", "classeonc_1_1Potential.html", "classeonc_1_1Potential" ],
      [ "potential_options_t", "structeonc_1_1potential__options__t.html", "structeonc_1_1potential__options__t" ],
      [ "PotentialConstructionScope", "classeonc_1_1PotentialConstructionScope.html", "classeonc_1_1PotentialConstructionScope" ],
      [ "PotRegistry", "classeonc_1_1PotRegistry.html", "classeonc_1_1PotRegistry" ],
      [ "prefactor_options_t", "structeonc_1_1prefactor__options__t.html", "structeonc_1_1prefactor__options__t" ],
      [ "PrefactorJob", "classeonc_1_1PrefactorJob.html", "classeonc_1_1PrefactorJob" ],
      [ "process_search_options_t", "structeonc_1_1process__search__options__t.html", "structeonc_1_1process__search__options__t" ],
      [ "ProcessSearchJob", "classeonc_1_1ProcessSearchJob.html", "classeonc_1_1ProcessSearchJob" ],
      [ "Quickmin", "classeonc_1_1Quickmin.html", "classeonc_1_1Quickmin" ],
      [ "replica_exchange_options_t", "structeonc_1_1replica__exchange__options__t.html", "structeonc_1_1replica__exchange__options__t" ],
      [ "ReplicaDynamicsJob", "classeonc_1_1ReplicaDynamicsJob.html", "classeonc_1_1ReplicaDynamicsJob" ],
      [ "ReplicaExchangeJob", "classeonc_1_1ReplicaExchangeJob.html", "classeonc_1_1ReplicaExchangeJob" ],
      [ "rgpot_options_t", "structeonc_1_1rgpot__options__t.html", "structeonc_1_1rgpot__options__t" ],
      [ "Runtime", "classeonc_1_1Runtime.html", "classeonc_1_1Runtime" ],
      [ "saddle_search_options_t", "structeonc_1_1saddle__search__options__t.html", "structeonc_1_1saddle__search__options__t" ],
      [ "SaddleSearchJob", "classeonc_1_1SaddleSearchJob.html", "classeonc_1_1SaddleSearchJob" ],
      [ "SaddleSearchMethod", "classeonc_1_1SaddleSearchMethod.html", "classeonc_1_1SaddleSearchMethod" ],
      [ "SafeHyperJob", "classeonc_1_1SafeHyperJob.html", "classeonc_1_1SafeHyperJob" ],
      [ "serve_options_t", "structeonc_1_1serve__options__t.html", "structeonc_1_1serve__options__t" ],
      [ "ServeEndpoint", "structeonc_1_1ServeEndpoint.html", "structeonc_1_1ServeEndpoint" ],
      [ "socket_nwchem_options_t", "structeonc_1_1socket__nwchem__options__t.html", "structeonc_1_1socket__nwchem__options__t" ],
      [ "SteepestDescent", "classeonc_1_1SteepestDescent.html", "classeonc_1_1SteepestDescent" ],
      [ "StructureComparisonJob", "classeonc_1_1StructureComparisonJob.html", "classeonc_1_1StructureComparisonJob" ],
      [ "StructureComparisonOptions", "structeonc_1_1StructureComparisonOptions.html", "structeonc_1_1StructureComparisonOptions" ],
      [ "SurrogatePotential", "classeonc_1_1SurrogatePotential.html", "classeonc_1_1SurrogatePotential" ],
      [ "tad_options_t", "structeonc_1_1tad__options__t.html", "structeonc_1_1tad__options__t" ],
      [ "TADJob", "classeonc_1_1TADJob.html", "classeonc_1_1TADJob" ],
      [ "TestJob", "classeonc_1_1TestJob.html", "classeonc_1_1TestJob" ],
      [ "thermostat_options_t", "structeonc_1_1thermostat__options__t.html", "structeonc_1_1thermostat__options__t" ],
      [ "VesinNeighbors", "classeonc_1_1VesinNeighbors.html", "classeonc_1_1VesinNeighbors" ],
      [ "X86DivRegs", "structeonc_1_1X86DivRegs.html", "structeonc_1_1X86DivRegs" ],
      [ "xtb_options_t", "structeonc_1_1xtb__options__t.html", "structeonc_1_1xtb__options__t" ],
      [ "XtsciOptimizer", "classeonc_1_1XtsciOptimizer.html", "classeonc_1_1XtsciOptimizer" ],
      [ "zbl_options_t", "structeonc_1_1zbl__options__t.html", "structeonc_1_1zbl__options__t" ],
      [ "ZBLRepulsiveIDPPObjective", "classeonc_1_1ZBLRepulsiveIDPPObjective.html", "classeonc_1_1ZBLRepulsiveIDPPObjective" ]
    ] ],
    [ "forcefields", "namespaceforcefields.html", [
      [ "zhu_philpott_parameters", "namespaceforcefields_1_1zhu__philpott__parameters.html", [
        [ "Standard", "structforcefields_1_1zhu__philpott__parameters_1_1Standard.html", "structforcefields_1_1zhu__philpott__parameters_1_1Standard" ],
        [ "Iceland", "structforcefields_1_1zhu__philpott__parameters_1_1Iceland.html", "structforcefields_1_1zhu__philpott__parameters_1_1Iceland" ]
      ] ],
      [ "Ccl", "classforcefields_1_1Ccl.html", "classforcefields_1_1Ccl" ],
      [ "PotentialBase", "classforcefields_1_1PotentialBase.html", "classforcefields_1_1PotentialBase" ],
      [ "SpceCcl", "classforcefields_1_1SpceCcl.html", "classforcefields_1_1SpceCcl" ],
      [ "Tip4p", "classforcefields_1_1Tip4p.html", "classforcefields_1_1Tip4p" ],
      [ "ZhuPhilpott", "classforcefields_1_1ZhuPhilpott.html", "classforcefields_1_1ZhuPhilpott" ]
    ] ],
    [ "AMS", "classAMS.html", "classAMS" ],
    [ "AMS_IO", "classAMS__IO.html", "classAMS__IO" ],
    [ "AsapPotential", "classAsapPotential.html", "classAsapPotential" ],
    [ "ASE", "classASE.html", "classASE" ],
    [ "ASENwchemPot", "classASENwchemPot.html", "classASENwchemPot" ],
    [ "ASEOrcaPot", "classASEOrcaPot.html", "classASEOrcaPot" ],
    [ "Atoms", "classAtoms.html", "classAtoms" ],
    [ "CatLearnPot", "classCatLearnPot.html", "classCatLearnPot" ],
    [ "CellList", "classCellList.html", "classCellList" ],
    [ "EAM", "classEAM.html", "classEAM" ],
    [ "EffectiveMediumTheory", "classEffectiveMediumTheory.html", "classEffectiveMediumTheory" ],
    [ "EMT", "classEMT.html", "classEMT" ],
    [ "emt_parameters", "structemt__parameters.html", "structemt__parameters" ],
    [ "EMTDefaultParameterProvider", "classEMTDefaultParameterProvider.html", "classEMTDefaultParameterProvider" ],
    [ "EMTParameterProvider", "classEMTParameterProvider.html", "classEMTParameterProvider" ],
    [ "EMTRasmussenParameterProvider", "classEMTRasmussenParameterProvider.html", "classEMTRasmussenParameterProvider" ],
    [ "EonMtaConfig", "structEonMtaConfig.html", "structEonMtaConfig" ],
    [ "EonMtaPot", "structEonMtaPot.html", "structEonMtaPot" ],
    [ "Exception", "classException.html", "classException" ],
    [ "ExtPot", "classExtPot.html", "classExtPot" ],
    [ "GhostAtoms", "classGhostAtoms.html", "classGhostAtoms" ],
    [ "GhostPotential", "classGhostPotential.html", "classGhostPotential" ],
    [ "GPRPotential", "classGPRPotential.html", "classGPRPotential" ],
    [ "Image", "structImage.html", "structImage" ],
    [ "istream", "classistream.html", null ],
    [ "LAMMPSPot", "classLAMMPSPot.html", "classLAMMPSPot" ],
    [ "MetatomicEngineLoader", "classMetatomicEngineLoader.html", "classMetatomicEngineLoader" ],
    [ "MetatomicEngineOptions", "structMetatomicEngineOptions.html", "structMetatomicEngineOptions" ],
    [ "MetatomicPotential", "classMetatomicPotential.html", "classMetatomicPotential" ],
    [ "MPIPot", "classMPIPot.html", "classMPIPot" ],
    [ "NeighborList", "classNeighborList.html", "classNeighborList" ],
    [ "ostream", "classostream.html", null ],
    [ "RgpotAdapter", "classRgpotAdapter.html", "classRgpotAdapter" ],
    [ "RGPotEngine", "classRGPotEngine.html", "classRGPotEngine" ],
    [ "RGPotEngineOptions", "structRGPotEngineOptions.html", "structRGPotEngineOptions" ],
    [ "RgpotMtaConfig", "structRgpotMtaConfig.html", "structRgpotMtaConfig" ],
    [ "RgpotMtaPot", "structRgpotMtaPot.html", "structRgpotMtaPot" ],
    [ "RgpotPot", "classRgpotPot.html", "classRgpotPot" ],
    [ "RgpotXtbConfig", "structRgpotXtbConfig.html", "structRgpotXtbConfig" ],
    [ "set", "classset.html", "classset" ],
    [ "SocketNWChemPot", "classSocketNWChemPot.html", "classSocketNWChemPot" ],
    [ "SpceCcl", "classSpceCcl.html", "classSpceCcl" ],
    [ "string", "classstring.html", "classstring" ],
    [ "stringstream", "classstringstream.html", null ],
    [ "SuperCell", "classSuperCell.html", "classSuperCell" ],
    [ "TinyMatrix", "classTinyMatrix.html", "classTinyMatrix" ],
    [ "Tip4p", "classTip4p.html", "classTip4p" ],
    [ "Tip4p_Pt", "classTip4p__Pt.html", "classTip4p__Pt" ],
    [ "VASP", "classVASP.html", "classVASP" ],
    [ "Vec", "classVec.html", "classVec" ],
    [ "vector", "classvector.html", "classvector" ],
    [ "XTBEngineLoader", "classXTBEngineLoader.html", "classXTBEngineLoader" ],
    [ "XTBEngineOptions", "structXTBEngineOptions.html", "structXTBEngineOptions" ],
    [ "XTBPot", "classXTBPot.html", "classXTBPot" ],
    [ "XtsciOptimizer", "classXtsciOptimizer.html", "classXtsciOptimizer" ]
];