name: Build and test eonclient with ASE
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
on: [push, pull_request]
permissions:
  contents: read
jobs:
  build_eon:
    runs-on: ${{ matrix.os }}
    name: test (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: prefix-dev/setup-pixi@a0af7a228712d6121d37aba47adf55c1332c9c2e # v0.9.4
        with:
          cache: true
          cache-write: true
          activate-environment: true
          environments: >-
            dev
      - name: Install cbindgen
        shell: bash
        run: command -v cbindgen || cargo install cbindgen
      - name: Install ASE
        shell: pixi run -e dev bash -e {0}
        run: pip install ase
      - name: Build eonclient with ASE
        shell: pixi run -e dev bash -e {0}
        run: |
          meson setup bbdir  \
          --prefix=$CONDA_PREFIX           \
          --buildtype release              \
          --libdir=lib                     \
          -Dwith_ase=True            \
          -Dwith_tests=True
          meson install --skip-subprojects -C bbdir
      - name: Run tests
        shell: pixi run -e dev bash -e {0}
        run: |
          meson test -C bbdir test_ase_pot
