name: Build eOn with GPRD
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
on:
  push:
    branches:
      - main

env:
  SCCACHE_GHA_ENABLED: "true"

jobs:
  build_eon:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup SSH for private submodule
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SUBMODULE_PRIVATE }}
      - name: Pull GPRD submodule
        run: |
          git clone git@github.com:TheochemUI/gpr_optim.git subprojects/gpr_optim
          cd subprojects/gpr_optim
          git checkout 26242c8e94569ef81103ece4662008c3250ada55
      - uses: prefix-dev/setup-pixi@v0.9.4
        with:
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
          activate-environment: true
          environments: >-
            dev
      - name: Configure sccache
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
      - name: Install cbindgen
        shell: bash
        run: command -v cbindgen || cargo install cbindgen

      - name: Install eon
        shell: pixi run bash -e {0}
        run: |
          meson setup --reconfigure bbdir  \
          --prefix=$CONDA_PREFIX           \
          --buildtype release              \
          --libdir=lib
          meson install -C bbdir
      - name: Integration Tests
        shell: pixi run bash -e {0}
        run: |
          cd client/gtests/data/saddle_search/
          eonclient
