name: Build basic eon
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
on: [push, pull_request]
jobs:
  build_eon:
    runs-on: ${{ matrix.os }}
    name: test (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        # TODO(rg): Handle the windows-2022 later, issues linking fmt
        # TODO(rg): Macos 12 seems to hang a lot, macos-12
        os: [ubuntu-22.04, macos-14]
    steps:
      - uses: actions/checkout@v4

      - uses: mamba-org/setup-micromamba@v1
        if: matrix.os != 'windows-2022'
        with:
          environment-file: lockfiles/dev-mta.conda-lock.yml
          environment-name: eongit
          init-shell: >-
            bash
          cache-environment: true
          cache-environment-key: environment-${{ matrix.os }}
          post-cleanup: 'all'
      - name: Compile and install [nix]
        if: matrix.os != 'windows-2022'
        shell: bash -el {0}
        run: |
          meson setup bbdir --prefix $CONDA_PREFIX --libdir=lib
          meson install -C bbdir

      - uses: mamba-org/setup-micromamba@v1
        if: matrix.os == 'windows-2022'
        with:
          environment-file: lockfiles/dev-mta.conda-lock.yml
          environment-name: eongit
          init-shell: >-
            powershell
          cache-environment: true
          cache-downloads: true
          cache-environment-key: environment-${{ matrix.os }}
          cache-downloads-key: downloads-${{ matrix.os }}
          post-cleanup: 'all'
      - name: Compile and install [windows]
        if: matrix.os == 'windows-2022'
        shell: pwsh
        run: |
          # Windows gfortran can't handle iso_c_binding...
          meson wrap install fmt
          meson setup bbdir --prefix $env:CONDA_PREFIX --libdir=lib -Dwith_cuh2=false
          meson install -C bbdir

      - name: Run tests
        shell: bash -el {0}
        run: |
          meson test -vvv -C bbdir
          # TODO(rg): Start running these after gh-143
          # cd examples/akmc-al
          # python -m eon.server
