name: Build and Deploy Documentation

concurrency:
  group: "pages"
  cancel-in-progress: true

on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
    # Check all PR
  schedule:
    - cron: '0 8 * * 1' # run every Monday at 8am UTC

env:
  SCCACHE_GHA_ENABLED: "true"

jobs:
  build_docs:
    name: Build documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: prefix-dev/setup-pixi@v0.9.4
        with:
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
          activate-environment: true
          environments: >-
            docs-mta

      - name: Configure sccache
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Build and install eonclient
        shell: pixi run -e docs-mta bash -e {0}
        run: |
          meson setup bbdir --prefix=$CONDA_PREFIX --libdir=lib \
            -Dwith_metatomic=True -Dtorch_version=2.10 -Dpip_metatomic=True
          meson install -C bbdir

      - name: Generate Docs
        shell: pixi run -e docs-mta bash -e {0}
        run: |
          pip install . --no-build-isolation
          sphinx-build -b html docs/source docs/build/html

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: docs/build/html/

      - name: Deploy
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html/
